### ISSUE TITLE
AppleWatch version?

### ISSUE THREAD

**Issue by daviddelmonte** [cbpowell/MarqueeLabel#101]
Charles, I'm using ML in an upcoming app. It's really useful. Is there any chance of a watch implementation? I have heard that scrolling within a WKTextView may be possible..

Thanks for your continued efforts on MarqueeLabel.
David

**Comment by cbpowell** [comment]
I haven't looked into WatchKit much, but I don't think this is possible yet…there's no CoreAnimation capability as far as I can tell, all animations are essentially pre-rendered GIFs. Might have to wait for "full" SDK access, which I think is a suspected announcement at WWDC. Definitely something to come back to later!
