### ISSUE TITLE
Attributed text

### ISSUE THREAD

**Issue by rzolin** [cbpowell/MarqueeLabel#103]
First of all thanks, this is a very good component. Though recently I have started using attributed string in many of my labels, and unfortunately MarqueeLabel doesn't support one yet. So maybe one of the next improvements you can add the support for NSAttributedText?

**Comment by cbpowell** [comment]
Glad you find it useful! Actually, MarqueeLabel does support attributed text, via the `attributedText` property it inherits from UILabel. You can see [an example in the demo project](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabelDemo/Classes/MarqueeLabelDemoViewController.m#L51-L63).

If you're having problems with a particular attributed string, let me know and I'll reopen so we can figure that issue out.

**Comment by rzolin** [comment]
That's strange, I used attributedText and the text wasn't animating. Replaced it with the regular one and it worked.

**Comment by cbpowell** [comment]
Ah that sounds like an issue then! Could you post an example that exhibits the problem? I assume you're running the latest version of MarqueeLabel?

**Comment by rzolin** [comment]
I used version 2.0 (set explicitly), then it was a simple setup of crating the label, assigning text and background colors (outside the attrib string), auto resize mask, hidden flag toggled to Yes (No - when displayed), and added as a subview to superview. And of course attribText is set.

**Comment by cbpowell** [comment]
Did you explicitly set 2.0.0 (or 2.0.x)? The current version is 2.2.3, and there have been a lot of fixes since 2.0.x.

**Comment by rzolin** [comment]
I set 2.0, saw it in github, will need to check the 2.2.3 then

**Comment by rzolin** [comment]
Still doesn't work, set version to 2.2.3 explicitly. And replacing `label.attributedText` with `label.text` works.
Here is the code:

```
- (void) displayLabelWithAttributedString:(NSAttributedString *) attributedString
{
    MarqueeLabel *label = (MarqueeLabel *) [self.view viewWithTag:STATUS_LABEL_VIEW_TAG];
    if (!label) {
        label = [self createStatusLabel];
    }

    label.attributedText = attributedString;
    label.hidden = NO;

//    [MarqueeLabel restartLabelsOfController:self];
    [label restartLabel];
}

- (void) hideLabel
{
    UILabel *label = (UILabel *) [self.view viewWithTag:STATUS_LABEL_VIEW_TAG];
    label.hidden = YES;
}

- (MarqueeLabel *) createStatusLabel
{
    MarqueeLabel *label = [[MarqueeLabel alloc] initWithFrame:self.navigationBar.frame duration:8.0 andFadeLength:10.0f];
    label.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
    label.tag = STATUS_LABEL_VIEW_TAG;
    label.numberOfLines = 1;
    label.hidden = YES;
    label.nuiClass = @"NavBarStatusLabel";
    [self.view addSubview:label];
    return label;
}
```

**Comment by cbpowell** [comment]
Hmm it all seems pretty normal - are you using it in a UINavigationBar? I'm wondering if the `hidden` property could be doing something, I don't think I've ever played with that with a MarqueeLabel.

I'd suggest setting breakpoints at these locations:
- [here](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L464),
- [here](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L468) (and check the value of the `labelTooLarge` variable),
- [here](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L474),
- [here](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L478), and
- [here](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L484)

It'll hit a lot of these points as your app loads the view, which is normal. The real question is if it hits any of these breakpoints immediately after your call to `restartLabel`. Basically if it hits a `return NO` line, that's what is preventing the scroll.

**Comment by rzolin** [comment]
I ask your forgiveness. I updated the Podfile version, but didn’t run `pod install`, was switching between tasks.
It is animating, but the background is transparent, though I specifically set it to some color. Though I noticed that the animation involves the whole view, when it ends animation to left, the background of the label (on the right) reveals what is beneath. So I probably need to wrap it in another view to prevent the indecent exposure :)

Thanks

**Comment by rzolin** [comment]
By the way, have you tried labels with 2+ lines of text? I am trying to use two lines, and setting numberOfLines to 2 or 0 doesn't help

**Comment by cbpowell** [comment]
No problem! Glad you found the issue.

As for having more than one line, that's not supported as of now. The goal of MarqueeLabel is to avoid needed to wrap text to a second line by allowing it to scroll across, so a single line is forced. It might be fairly straightforward to modify the code to allow multiple lines for your particular use case though.
