### ISSUE TITLE
Find out text on Label tap

### ISSUE THREAD

**Issue by iamabhiee** [cbpowell/MarqueeLabel#106]
Is it possible to find-out which text is currently visible on label tap?

**Comment by cbpowell** [comment]
Unfortunately no, not at the moment. I'd suggest looking into Zac West's [ZSWTappableLabel](https://github.com/zacwest/ZSWTappableLabel) and perhaps combining some of that code with MarqueeLabel?

**Comment by iamabhiee** [comment]
Or tableview like datasource delegate approach?

**Comment by cbpowell** [comment]
I assume you're trying to have something like scrolling headlines, but MarqueeLabel wasn't really built for that. Your best option would probably be to use a horizontal UICollectionView with UILabels in the collection view cells. This gets you a datasource and delegate interface, and it'll be easier to get tap notifications.
