### ISSUE TITLE
All custom settings of label are reset in some cases

### ISSUE THREAD

**Issue by 666tos** [cbpowell/MarqueeLabel#107]
My scenario is:

@implementation MyTableViewCell

- (void)awakeFromNib
{
    [super awakeFromNib];
    
     self.label.textColor = [UIColor colorWithHEX:0x515151FF];
     self.detailLabel.textColor = [UIColor colorWithHEX:0x8A8A8AFF];
    
    self.label.font = //Some font
    self.detailLabel.font = //Some font
}

So what happens here: when cell is awaken, it sets some properties to label, which is initialized with coder, but still not awaken. It receives calls to -setTextColor: and -setFont: , does not call super's implementation and then after it gets awaken it performs -forwardPropertiesToSubLabel and resets all set properties to super's values

**Comment by 666tos** [comment]
Also, text set from storyboard still visible on background

**Comment by cbpowell** [comment]
Ah yeah, I see the same thing when I set up a cell like you did. However I'm not able to replicate seeing the Storyboard-set text after changing it, seems to clear for me (the `forwardPropertiesToSublabel` call should clear it by setting `super.attributedText = nil`). Are you using the latest version of MarqueeLabel? That was an issue from a much older version. 

I think I've found a fix for fonts/colors/etc set during `awakeFromNib` that doesn't cause any side effects. In the interim, is there any reason you can't just set the colors and fonts you're setting in `awakeFromNib`  in Interface Builder instead? That should fix the issue.

**Comment by cbpowell** [comment]
I've pushed the tentative fix to the [dev branch](https://github.com/cbpowell/MarqueeLabel/tree/dev), give it a try and see if it helps your issue.

**Comment by cbpowell** [comment]
Went ahead and pushed the fix to master in [version 2.2.5](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.2.5). This should fix your issue with setting the major properties inside `awakeFromNib` - let me know if it works for you!

**Comment by cbpowell** [comment]
I'm assuming this is fixed - let me know if that's not the case!
