### ISSUE TITLE
[suggestion] update instructions

### ISSUE THREAD

**Issue by frakman1** [cbpowell/MarqueeLabel#109]
Great library. Thank you so much for making it possible. I've used it in my project and it works like a charm.  Just a couple of suggestions:

-For UIBuilder/Storyboard approach:
At first, I couldn't link it to any of my properties and I couldn't make a new one with the MarqueeLabel class. It would only let me select UILabel. Then I realised that I had to click on my label in the storyboard, goto Identity Inspector, then change its class from UILabel to MarqueeLabel. 

-Maybe add some animated gifs of your demo viewcontroller in action?

Otherwise, your instructions in the readme are TOP NOTCH. Rarely do I find such helpful instructions. Great work.

**Comment by cbpowell** [comment]
Good suggestions, thanks! And glad you found the rest helpful!

**Comment by cbpowell** [comment]
Added your suggestions in commit 6c8e6f4 - thanks!

**Comment by frakman1** [comment]
Excellent!
