### ISSUE TITLE
MarqueeLabel Scroll

### ISSUE THREAD

**Issue by SintoAntony** [cbpowell/MarqueeLabel#111]
i need MarqueeLabel scroll right to left only after that it must to reset.

**Comment by cbpowell** [comment]
Check out the demo implementation, there are examples of all the scrolling types including right to left. That should get you started!

I don't know exactly what you want to do, but if you want to manually control when the label scrolls, set the [`holdScrolling`](http://cocoadocs.org/docsets/MarqueeLabel/2.2.5/Classes/MarqueeLabel.html#//api/name/holdScrolling) property to `YES`. You can then manually trigger when the scroll should start with [`triggerScrollStart`](http://cocoadocs.org/docsets/MarqueeLabel/2.2.5/Classes/MarqueeLabel.html#//api/name/triggerScrollStart). The [`restartLabel`](http://cocoadocs.org/docsets/MarqueeLabel/2.2.5/Classes/MarqueeLabel.html#//api/name/restartLabel) method can also be used to return the label to the "home" position at any time.
