### ISSUE TITLE
Animation has a pause

### ISSUE THREAD

**Issue by codesourse** [cbpowell/MarqueeLabel#112]
Animation has a pause,And red color have some mistake. 

    NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:@"祝沈明亮同学荣获本届选美比赛第一名，孙善明第二名，黄磊第三名。well done!!!"];
    [attributedString addAttribute:NSForegroundColorAttributeName value:[UIColor redColor] range:NSMakeRange(0, 3)];

    self.demoLabel6.tag = 601;
    self.demoLabel6.marqueeType = MLContinuous;
    self.demoLabel6.scrollDuration = 15.0f;
    self.demoLabel6.fadeLength = 10.0f;
    self.demoLabel6.trailingBuffer = 30.0f;

**Comment by cbpowell** [comment]
[Release v2.3.0](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.3.0) should fix this one as well.
