### ISSUE TITLE
Force a scroll with a string that fits inside the label bounds

### ISSUE THREAD

**Issue by RGSSoftware** [cbpowell/MarqueeLabel#113]
From - (void)triggerScrollStart docs - 
"This method will not force a label with a string that fits inside the label bounds (i.e. that would not automatically scroll) to begin a scroll animation."

Do you have an implementation that will force a scroll with a string that fits inside the label bounds?

**Comment by RGSSoftware** [comment]
I've figured out an implementation.

**Comment by cbpowell** [comment]
Sounds good - I've always resisted adding that type of functionality to MarqueeLabel, because the intent of the library is to mimic Apple's implementation.
