### ISSUE TITLE
font will become bigger

### ISSUE THREAD

**Issue by codesourse** [cbpowell/MarqueeLabel#114]
The next cycle fonts bigger.

**Comment by codesourse** [comment]
- (void)refreshSubLabels:(NSArray *)subLabels {
    for (UILabel *sl in subLabels) {
        if (sl.tag == 700) {
            // Do not overwrite base subLabel properties
            continue;
        }

        sl.backgroundColor = self.backgroundColor;
        //sl.textColor = self.textColor;
        sl.shadowColor = self.shadowColor;
        sl.shadowOffset = self.shadowOffset;
        sl.textAlignment = NSTextAlignmentLeft;
        sl.attributedText = self.attributedText;
    }
}
please add "        sl.font=self.font;"

**Comment by cbpowell** [comment]
Sorry for the delay on this, but I believe [release v2.3.0](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.3.0) should fix this issue!
