### ISSUE TITLE
UILabel width limitation different on iPhone 6(s)+

### ISSUE THREAD

**Issue by FransGH** [cbpowell/MarqueeLabel#118]
I just discovered the hard way that the UILabel rendering limit on the iPhone 6(s)+ is not 8192 but 2/3 of that, 5461 points. 

- (CGSize)subLabelSize {
    ...
    expectedLabelSize.width = ceil(MIN(expectedLabelSize.width, 8192.0f));
    ...
}

Actually not using your plugin but stumbled on this issue in my own code. Was hoping your code didn't suffer from this length limitation :-)

**Comment by cbpowell** [comment]
Thanks for letting me know! I wonder if the difference is due to the extra pixels (before downscaling) that the 6+ renders…
