### ISSUE TITLE
shadowOffset Not Respected

### ISSUE THREAD

**Issue by stuartjmoore** [cbpowell/MarqueeLabel#119]
Two labels, same shadow settings, `UILabel` above and `MarqueeLabel` below:

<img width="220" alt="screen shot 2015-10-29 at 7 38 43 am" src="https://cloud.githubusercontent.com/assets/642708/10817442/2bdade6e-7e10-11e5-9812-9e37c1d5630f.png">

The `shadowOffset` of the `MarqueeLabel` is the default -1, not the storyboard set 1.

**Comment by cbpowell** [comment]
Looks like the method I was using to pull `shadowOffset` from the value set via IB wasn't working - should be fixed now in 2.3.4. Thanks!
