### ISSUE TITLE
Repeat limit

### ISSUE THREAD

**Issue by codyrotwein** [cbpowell/MarqueeLabel#121]
Is there a way to only have the marquee text repeat twice instead of indefinitely?

**Comment by codyrotwein** [comment]
I was able to subclass the library and override the labelReturnedToHome method in order to achieve what I needed:

class MarqueeLabelNoRepeat: MarqueeLabel {
    let repeatCount = 2
    var scrollCount = 0
    override func labelReturnedToHome(finished: Bool) {
        scrollCount++
        if scrollCount == repeatCount {
            // stop scrolling
            super.pauseLabel()
            scrollCount = 0
        }
    }
}

**Comment by cbpowell** [comment]
Awesome, glad that worked!

**Comment by sbrioux** [comment]
I have tried this approach but it doesn't seem to be stopping the animation.  Might it have anything to do with being in a UITableViewCell?

```swift
class CustomMarqueeLabel: MarqueeLabel {
    var maxNumOfScrolls = 1

    var currentNumOfScrolls = 0

    override func labelReturnedToHome(_ finished: Bool) {
        super.labelReturnedToHome(finished)
        currentNumOfScrolls += 1

        if currentNumOfScrolls >= maxNumOfScrolls {
            super.pauseLabel()
            currentNumOfScrolls = 0
        }

        os_log("label finished and returned to home %d", log: .default, type: .debug, currentNumOfScrolls)
    }
}
```

Ideas?
