### ISSUE TITLE
Couldn't display very long text in Marquee Label  

### ISSUE THREAD

**Issue by nareshnesh** [cbpowell/MarqueeLabel#125]
I installed the Library via pod and followed all the step to set up the Marquee label in my view controller, my text is dynamic text which i appended from JSON call , i couldn't display the text in the screen .However  reducing the text length to half or so , the marquee label is displaying the text.
Please tell me how to fix this issue.

**Comment by cbpowell** [comment]
I think you're probably running into an iOS limitation (as far as I can tell). UILabels have an upper size limit, and above that size they just don't render at all. Check out #96 and #118. MarqueeLabel works by expanding the `subLabel` to fit the text, so if your text is too long you'll run into this problem. You'll need to reduce the length of your text.
