### ISSUE TITLE
Improvement: Non repeatable text support

### ISSUE THREAD

**Issue by Vulivadmin** [cbpowell/MarqueeLabel#127]
Can we have a non-repeatable text in the label? i.e. Once a cycle of text has finished scrolling, the user shouldn't see the starting word of the text at the end of it.

**Comment by cbpowell** [comment]
This is a little outside of the scope I envision for MarqueeLabel (which is to replicate Apple's private marquee label), but I can see how it could be useful for some applications. Unfortunately I don't think the present MarqueeLabel architecture would support it without a lot of work.

If you see a good way to do it, please feel free to submit a pull request!
