### ISSUE TITLE
cannot set rate in storyboard

### ISSUE THREAD

**Issue by PMExtra** [cbpowell/MarqueeLabel#132]
Failed to set (scrollRate) user defined inspected property on (MarqueeLabel_Swift.MarqueeLabel): [<MarqueeLabel_Swift.MarqueeLabel 0x7fb672c7aab0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key scrollRate.

MarqueeLabel-Swift  2.6.6

**Comment by cbpowell** [comment]
Thanks! I hadn't even noticed those weren't working. The issue was that you can't have Optionals as IBInspectable properties, so they're now just normal CGFloats.
