### ISSUE TITLE
Change max width of UILabel on tvOS

### ISSUE THREAD

**Issue by florianweich** [cbpowell/MarqueeLabel#134]
There is a width restriction of 5461.0 that applies to the iPhone 6 Plus, but does not apply to the Apple TV. I am using MarqueeLabel as a ticker view for news headlines and the max width seems to be at around 16000.0 on Apple TV.
Please consider changing this in a future release.

**Comment by cbpowell** [comment]
Thanks for the info, good to know! Did you happen to determine the exact value?

**Comment by cbpowell** [comment]
Determined it with some testing, the limit is 16384.0 points.
