### ISSUE TITLE
Does MarqueeLabel support scrolling only once and supply a Block/Notification?

### ISSUE THREAD

**Issue by zhouxiangzhong** [cbpowell/MarqueeLabel#135]
In my app, I want to set a long text to MarqueeLabel, scrolling from left to right only once, and when the end of the text reaches the right edge of MarqueeLabel，it stops scrolling and post a notification(or block/delegate), so that I can remove/hide the MarqueeLabel...
Can MarqueeLabel support this kind of feature please?

**Comment by RobertNNms** [comment]
Hi,

+1 

I have a very long text....and unfortunately the text is cut...
Have you a solution ?

Regards

**Comment by cbpowell** [comment]
@zhouxiangzhong Unfortunately I don't think that's easily possible with the current design. The left-right/right-left scrolls work with a continuous animation, so there's not really a point at which to call a notification/block. What you're looking for could probably be easily achieved with regular UIView animations and a UILabel inside another UIView though!

@RobertNNms After a certain size, UIKit will stop rendering UILabels. MarqueeLabel attempts to protect you from this by limiting the sublabel frame size to the largest size at which the label will still draw, and the text is clipped at that point. As far as I know there isn't a way around this limit. That said, on the AppleTV the limit is much higher (see #134), and I need to up the limit specifically for tvOS.
