### ISSUE TITLE
Not looping anymore...

### ISSUE THREAD

**Issue by Foddy** [cbpowell/MarqueeLabel#137]
Hi, since the last update of MarqueeLabel my labels are not looping the animation anymore. Take a look at my settings on Storyboard. Did I forgot some new settings for looping?

![setings](https://cloud.githubusercontent.com/assets/5302050/14978645/8b613a22-111d-11e6-90a6-d4dcbecc3dd3.png)

Thanks

**Comment by cbpowell** [comment]
Whoops, looks like there's an issue I didn't notice! I'll take a look tonight, in the interim you can go back to the [2.7.1 release](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.7.1) if you need.

**Comment by cbpowell** [comment]
It was a stupid mistake! Scroll animations which didn't finish (happens frequently with MarqueeLabel, as part of the design) were clearing the completion block for the animations that _would_ finish. Without a completion block, there was no subsequent scroll animation fired. Thanks for the heads up!
