### ISSUE TITLE
not work on iOS 10 beta

### ISSUE THREAD

**Issue by duyquang91** [cbpowell/MarqueeLabel#143]
not work on iOS 10 beta

**Comment by cbpowell** [comment]
Hi! I assume you mean with Swift 2.3 and/or Swift 3.0? I'll probably be pushing a compatible version to a dev branch in the next couple days.

**Comment by duyquang91** [comment]
Object C with xcode 8 beta



On Fri, Jun 17, 2016 at 9:11 AM +0700, "Charles Powell" <notifications@github.com> wrote:












Hi! I assume you mean with Swift 2.3 and/or Swift 3.0? I'll probably be pushing a compatible version to a dev branch in the next couple days.

**Comment by cbpowell** [comment]
I don't have any issues running the Objective-C demo project in Xcode 8/iOS 10.0. What errors are you seeing?

**Comment by duyquang91** [comment]
My issue is label not auto scrolling

Get Outlook for iOS




On Sat, Jun 18, 2016 at 4:27 AM +0700, "Charles Powell" <notifications@github.com> wrote:












I don't have any issues running the Objective-C demo project in Xcode 8/iOS 10.0. What errors are you seeing?

**Comment by cbpowell** [comment]
You'll have to provide some details about your implementation. Scrolling works fine in the demo project.

**Comment by cbpowell** [comment]
I'm going to go ahead and close this, but please feel free to reply with more details if you're still having a problem!

**Comment by duyquang91** [comment]
it work perfect now thanks you

2016-06-26 0:50 GMT+07:00 Charles Powell <notifications@github.com>:

> I'm going to go ahead and close this, but please feel free to reply with
> more details if you're still having a problem!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cbpowell/MarqueeLabel/issues/143#issuecomment-228561862>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOpVdGLvLQkKKD5DrwCRk8Pr5aP9rzfQks5qPWpXgaJpZM4I3DAt>
> .
>



-- 

Đào Duy Quang - iOS Developer
