### ISSUE TITLE
Could use Swift 3 version when ready.

### ISSUE THREAD

**Issue by daviddelmonte** [cbpowell/MarqueeLabel#145]
Thanks Charles, I tried to use / update the existing swift file to Swift 3, but I think it's better left to you, when you think it appropriate..

**Comment by cbpowell** [comment]
I gave the conversion tool a shot (plus some additional work) and it resulted in the [swift-3.0 branch](https://github.com/cbpowell/MarqueeLabel/tree/swift-3.0), which seems to mostly work? Give it a shot! As Swift 3.0 becomes more final I'm sure it'll need some updates.

**Comment by daviddelmonte** [comment]
Thanks Charles.. I've just started using beta2 of Sierra.  I opened the MarqueeLabelSwift file. If I try to compile the framework, I get over 100 errors. If I compile just the demo app, I get about 5 or so errors. I think a lot has changed between the releases.. Perhaps it would be prudent to wait a bit longer .. I imagine many more changes are to come.. I do appreciate the effort!

David

**Comment by cbpowell** [comment]
Very possible! I just got around to downloading Xcode 8 beta 2 last night, and didn't take a look at the Swift 3.0 branch. I'll see what's changed in the next day or two.

**Comment by cbpowell** [comment]
Going to close this - check out the [Swift 3.0](https://github.com/cbpowell/MarqueeLabel/tree/swift-3.0) branch which I'll try to keep up to date as the new betas a released!

**Comment by daviddelmonte** [comment]
Thanks Charles!
