### ISSUE TITLE
Issues with 2.7.8 and other updates

### ISSUE THREAD

**Issue by GabeJacobs** [cbpowell/MarqueeLabel#150]
Hey!

First, just want to say thank you for working on this project! It's amazing!

With 2.7.8 though, we've noticed that the labels do not have any trailing buffer when scrolling. It therefore looks like one long word even though it isn't.

Don't take this the wrong way, but It would be really appreciated if there was more testing done before release. I've noticed a lot of issues that come about when letting cocoapods update automatically. Maybe do what a lot of repos do which is release betas of the library before making it a stable release. This way we can test the updated before auto upgrading.

Again thanks so much!

- Gabe

**Comment by cbpowell** [comment]
Glad you find it useful!

Can you give some more details about not seeing a (functional) trailing buffer in your implementation? In the demo project, [`demoLabel5`](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabelSwift/MarqueeLabelDemoViewController.swift#L100) uses only a trailing buffer and I don't see any issues there. [`demoLabel3`](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabelSwift/MarqueeLabelDemoViewController.swift#L79) also uses both a leading and a trailing buffer.

As for increased testing - I sympathize and of course want to improve MarqueeLabel without introducing errors, but that's additional work and time for me. For big changes, I definitely see your point and will keep it in mind.

But in general I would consider it a good practice to avoid blindly autoupdating. Once you have a successful setup without any known issues, it's on you to assess the impacts of updates to the libraries you use...even if they are just claimed to be just minor patches (by maintainers like me, who have no idea about the details of your specific usage/implementation).

**Comment by cbpowell** [comment]
Going to close this one - but if you have more issues with the trailing buffer, please give an update and I can reopen it!
