### ISSUE TITLE
Strange case where MarqueeLabel scrolls when it shouldn't

### ISSUE THREAD

**Issue by mrezk** [cbpowell/MarqueeLabel#151]
Hi @cbpowell, I found a strange case where a label with enough space is scrolling.
I could reproduce the issue on iPhone 6 plus and 6s plus using the following project:
[NonIntegerWidthLabel2.zip](https://github.com/cbpowell/MarqueeLabel/files/398158/NonIntegerWidthLabel2.zip).

I could narrow down the problem to this line:
```objc
labelTooLarge = ([self subLabelSize].width + self.leadingBuffer > self.bounds.size.width)
```

It seems that when `[self subLabelSize].width` is `X + 2/3` (e.g.: 101.666667 on the example project), somewhere precision is lost and when comparing it to `self.bounds.size.width` it turns out the comparison is YES when it shouldn't.   

This is the debugger output on the moment the previous line is executed:
```
(lldb) expr [self subLabelSize].width
(CGFloat) $1 = 101.66666666666667
(lldb) expr self.bounds.size.width
(CGFloat) $2 = 101.66666666666666
```

Please let me know if there is any other info I can provide to help solving this issue.
Cheers,
Mariano

**Comment by cbpowell** [comment]
Wow that's quite the edge case! I mean that's a 0.1*10E-13 difference in size, I'm assuming it's getting into the weeds of CGFloat resolution. I expect the fix will be to use the appropriate epsilon value when doing the check to avoid the potential ambiguity at that resolution, and NOT scroll unless the size label is larger than the width by at least 1x epsilon. I'll try it out with your sample project - thanks for providing that!

**Comment by cbpowell** [comment]
Using a `FLT_EPSILON` in the width comparison seems to fix it - thanks for the heads up!

**Comment by mrezk** [comment]
@cbpowell my pleasure. Thanks for the great support 😄👍👍
