### ISSUE TITLE
Restart scrolling when text ends

### ISSUE THREAD

**Issue by robcas3** [cbpowell/MarqueeLabel#153]
How is it possible restart the animation when text reaches the end? 
i'm using LeftRight type

**Comment by cbpowell** [comment]
Are you looking to reset the text back to the "home" (starting) position when it reaches the "away" (maximum left) position? As in you skip the scrolling-back-right animation?

**Comment by robcas3** [comment]
Yes, exactly that! back to home when reaches away
(Thanks for the quick reply, by the way!)

**Comment by cbpowell** [comment]
No problem! Unfortunately there isn't a very clean way to do this right now. The animations are pre-built with the "loop" (in the case of LeftRight, the scrolling-back-right) with no callback or anything at the halfway point to catch it before the second half begins. Just to be sure, you're *not* looking for the continuous-type scrolling, which is the way Apple's labels work?

Your best short-term option might be to take the value of your animation duration + delay, create a timer with that value, and fire it at the same time the animation starts.

Something like this I think…note that I didn't actually run this code:
```swift
// So you can "manually" control when the first scroll starts
aLabel.holdScrolling = true
// Schedule a timer to call a handler function on a (duration + delay) interval
let timer = NSTimer.scheduledTimerWithTimeInterval((duration + delay), target: self, selector: #selector(labelHandler), userInfo: nil, repeats: true)
// Then immediately change holdScrolling to false to trigger scroll and allow "automatic" scrolling
aLabel.holdScrolling = false;

// Elsewhere…
func labelHandler() {
    aLabel.restartLabel()
}
// And kill the NSTimer whenever appropriate

**Comment by kulakoff83** [comment]
Hi,i have same question, but if i use label.speed = .rate(40) timer is not helped me. In old version you have delegate from this...

**Comment by cbpowell** [comment]
Hi @kulakoff83 - the older versions used two separate animations for scrolling, but starting with release 2.0.0 a single animation is used for both halves of the animation (home --> away, and away --> home) which simplified the animation handling. CoreAnimation doesn't provide callbacks at arbitrary points in the animation, so there's unfortunately nothing to pass on to a delegate either.

The best way I can think of is something like what I put in the comment above, where you use your delay and duration values to fire a timer. There might be a better way to do that approach with a MarqueeLabel subclass, which I'll try to follow up with later.

**Comment by cbpowell** [comment]
Better late that never, but here's a subclass that does what @robcas3 requested (I think). This does however require a change that I'll incorporate into MarqueeLabel 3.0.1 - the `animationDuration` property is currently marked `private` (in the Swift version, similar for Obj-C), but I'm going to change it to `private(set) public` such that it can be accessed for use, but not externally set.

I mentioned this in PR #148, but I'll add this as the first subclass/extension in a new list of often-requested modifications to MarqueeLabel that aren't incorporated into the master repo.

```swift
//
//  NoAnimationReturn.swift
//  MarqueeLabel
//
//  Created by Charles Powell on 10/23/16.
//  Copyright © 2016 Charles Powell. All rights reserved.

import UIKit
import MarqueeLabel

open class NoAnimationReturn: MarqueeLabel {
    // Override labelWillBeginScroll to catch when a scroll animation starts
    override open func labelWillBeginScroll() {
        // This only makes sense for leftRight and rightLeft types
        if type == .leftRight || type == .rightLeft {
            // Calculate "away" position time after scroll start
            let awayTime = animationDelay + animationDuration
            // Schedule a timer to restart the label when it hits the "away" position
            Timer.scheduledTimer(withTimeInterval: TimeInterval(awayTime), repeats: false, block: { (timer) in
                self.restartLabel()
            })
        }
    }
}

**Comment by kulakoff83** [comment]
Thanks, I done something similar in "override open var text: String?" and added delegate.

**Comment by cbpowell** [comment]
I've added an "Extras" folder that now contains this subclass. Hope it helps!

**Comment by sandeepk000** [comment]
> Better late that never, but here's a subclass that does what @robcas3 requested (I think). This does however require a change that I'll incorporate into MarqueeLabel 3.0.1 - the `animationDuration` property is currently marked `private` (in the Swift version, similar for Obj-C), but I'm going to change it to `private(set) public` such that it can be accessed for use, but not externally set.
> 
> I mentioned this in PR #148, but I'll add this as the first subclass/extension in a new list of often-requested modifications to MarqueeLabel that aren't incorporated into the master repo.
> 
> ```swift
> //
> //  NoAnimationReturn.swift
> //  MarqueeLabel
> //
> //  Created by Charles Powell on 10/23/16.
> //  Copyright © 2016 Charles Powell. All rights reserved.
> 
> import UIKit
> import MarqueeLabel
> 
> open class NoAnimationReturn: MarqueeLabel {
>     // Override labelWillBeginScroll to catch when a scroll animation starts
>     override open func labelWillBeginScroll() {
>         // This only makes sense for leftRight and rightLeft types
>         if type == .leftRight || type == .rightLeft {
>             // Calculate "away" position time after scroll start
>             let awayTime = animationDelay + animationDuration
>             // Schedule a timer to restart the label when it hits the "away" position
>             Timer.scheduledTimer(withTimeInterval: TimeInterval(awayTime), repeats: false, block: { (timer) in
>                 self.restartLabel()
>             })
>         }
>     }
> }
> ```

there is problem with this if i have multiple scrolling labels then first label timer isrestrating second label also.please help.
