### ISSUE TITLE
iOS 10 support

### ISSUE THREAD

**Issue by martinobonfiglioli** [cbpowell/MarqueeLabel#154]
Please add support for iOS 10 and for new vibrancy effects:

- widgetPrimaryVibrancyEffect
- widgetSecondaryVibrancyEffect

Thanks!

**Comment by cbpowell** [comment]
I think all that needed to be added was support for `tintColor` and the `tintColorDidChange` function - can you try out the [dev](https://github.com/cbpowell/MarqueeLabel/tree/dev)/[swift-2.3](https://github.com/cbpowell/MarqueeLabel/tree/swift-2.3)/[swift-3.0](https://github.com/cbpowell/MarqueeLabel/tree/swift-3.0) branch (whichever you're working with) to see if it works for you?

**Comment by martinobonfiglioli** [comment]
Yes _dev_ branch works for me! Thanks

**Comment by cbpowell** [comment]
Merged into master, and will eventually be release 2.8.0 on Cocoapods (which seems to be having some server issues right this moment)!
