### ISSUE TITLE
tvOS 10 and Swift 3

### ISSUE THREAD

**Issue by legomanfish** [cbpowell/MarqueeLabel#158]
Hey,

We try to use MarqueeLabel on our projects but we can't compile the tvOS target with the last version of Xcode (GM build) and Swift 3.
Can you fix it?

Thanks!

Regards,

**Comment by cbpowell** [comment]
The current master build (i.e. from Cocoapods) is still using Swift 2.2, which is not compatible with Swift 3.0. Have you tried the [preliminary Swift 3.0 branch](https://github.com/cbpowell/MarqueeLabel/tree/swift-3.0)?

**Comment by legomanfish** [comment]
Yes I was on the Swift 3 branch.
No problem with the iOS target, just with the tvOS target.

**Comment by cbpowell** [comment]
Looks like the Swift conversion tool only updated the demo target to use Swift 3.0 (rather than legacy swift), and not the framework target. Believe this should be fixed now, thanks!
