### ISSUE TITLE
How to point to swift3.0 branch?

### ISSUE THREAD

**Issue by fprosper** [cbpowell/MarqueeLabel#161]
I am trying this but it is not working

pod 'MarqueeLabel/Swift', git: => 'https://github.com/cbpowell/MarqueeLabel.git', :branch => 'swift3'

**Comment by Chrisdf** [comment]
I got it to install using this:

pod 'MarqueeLabel/Swift', :git => 'https://github.com/cbpowell/MarqueeLabel.git', :branch => 'swift-2.3'

**Comment by cbpowell** [comment]
@fprosper The branch is actually 'swift-3.0', emphasis on the dash between swift and 3.0, I think that might fix it?

**Comment by fprosper** [comment]
Thank you @cbpowell. Do you plan to put in on the main branch any time soon?

**Comment by karthikgollapudi** [comment]
I believe the colon comes before the word git instead of after @fprosper 

`pod 'MarqueeLabel/Swift', :git => 'https://github.com/cbpowell/MarqueeLabel.git', :branch => 'swift-3.0'`

**Comment by cbpowell** [comment]
@fprosper just pushed [release 3.0.0](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.0.0) with Swift 3.0 support!

**Comment by fprosper** [comment]
Thanks!
