### ISSUE TITLE
2.8.0 not released?

### ISSUE THREAD

**Issue by szweier** [cbpowell/MarqueeLabel#162]
Looks like CHANGELOG shows 2.8.0 but I can't seem to point to it in my Podfile. 2.8.0 will provide support for using Xcode 8 correct?

**Comment by Chrisdf** [comment]
This will point to Swift 2.3, which will provide support for xcode 7/8

pod 'MarqueeLabel/Swift', :git => 'https://github.com/cbpowell/MarqueeLabel.git', :branch => 'swift-2.3'

**Comment by cbpowell** [comment]
@szweier The other day when I tried to publish release 2.8.0 to Cocoapods they were having some server issues (as far as I could tell), and then I forgot to follow up! I'll try again a little later today. @Chrisdf's approach should work in the interim.

**Comment by cbpowell** [comment]
Release 2.8.0 _should_ be live now...I still had some issues publishing it, but `pod try` pulled the 2.8.0 version.
