### ISSUE TITLE
Swift 3.0 pod spec should tell cocoa pods to set the legacy flag to no

### ISSUE THREAD

**Issue by szweier** [cbpowell/MarqueeLabel#164]
The pod spec would ned to contain something like this.

`s.xcconfig         = { 'SWIFT_VERSION' => '3.0' }`

**Comment by cbpowell** [comment]
Thanks! I tried that and couldn't get it to work…not sure why, the Swift 3.0 cocoapods documentation is a little sparse as of right now. But I did use the method of adding a `.swift-version` file to the pod directory and that seemed to make it work.
