### ISSUE TITLE
 MarqueeLabel.text lenth shorter than the MarqueeLabel width

### ISSUE THREAD

**Issue by lilin87788** [cbpowell/MarqueeLabel#167]
i want MarqueeLabel scroll  when MarqueeLabel.text lenth shorter than the MarqueeLabel width

**Comment by cbpowell** [comment]
That's not currently supported, sorry! But [this fork](https://github.com/cbpowell/MarqueeLabel/pull/148) implements a version of the functionality. It's a little behind the master repo now, so you'd need to apply the changes to the latest code manually.

**Comment by lilin87788** [comment]
thank you for reply me, and i hope the repo will surpported this in future
