### ISSUE TITLE
Single shot scrolling without returning to home or repeating text.

### ISSUE THREAD

**Issue by dillan** [cbpowell/MarqueeLabel#168]
I am wondering if there is a way to get the following behavior from Marquee Label:

```
|ABC DEF| <-- Start Scrolling
|BC DEF |
|C DEF  |
| DEF   |
|DEF    |
|EF     |
|F      |
|       | <-- End Scrolling. Note: Does not return to home position.
```

Basically, I'm looking for it to scroll across one time, without repeating text or returning to the home position. I would also need to know when the text has completed scrolling across, similar to `-[MarqueeLabel labelReturnedToHome:]`, but without the label actually returning to the home position.

**Comment by cbpowell** [comment]
Hmm, you could probably get that functionality with some smart manipulation? I think you could set the `trailingBuffer` to a value greater than or equal to your frame width, and then you'd need to use `pauseLabel` to pause it while "out of bounds". That'd be the trickier part, you'd need to use a timer to fire a call to `pauseLabel` at the correct time after scroll start. The correct time would depend on the MarqueeType and your scroll duration and delay values.

A subclass of MarqueeLabel would probably be the best way to handle it, so you could override `labelWillBeginScroll` and fire the timer there, plus easily access the duration + delay values.

**Comment by cbpowell** [comment]
There was a very similar question on issue #153, and I posted a subclass snippet that's functionally close. It looks like you're using Objective-C rather than Swift, but the logic would be the same. Instead of calling `self.restartLabel()`, you would want to call `self.pauseLabel()`.

**Comment by cbpowell** [comment]
I've added an "Extras" folder that [contains my suggestion](https://github.com/cbpowell/MarqueeLabel/blob/master/Extras/SingleShotOffscreenLabel.swift) on how to achieve this - it's admittedly in Swift, but it should be super easy to convert to Objective-C. Hope it helps!

**Comment by dillan** [comment]
@cbpowell thank you very much for sharing this.
