### ISSUE TITLE
Convert to current swift syntax?

### ISSUE THREAD

**Issue by Grimbode** [cbpowell/MarqueeLabel#169]
Installed MarqueeLabel/Swift via the CocoaPods App and upon opening my project I get the message:

> Convert to Current Swift Swift Syntax?
> The target “MarqueeLabel” contains source code developed with an earlier version of Swift.
> 
> Choose “Convert” to update the source code in this target to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3.
> 
> This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu.

Is this normal for Swift 3.0 compatibility?

`pod 'MarqueeLabel/Swift'` automatically installs the 2.7.9 version, an error occurs when I specify `'~> 3.0.1'` it doesn't install.

Thank you.

**Comment by cbpowell** [comment]
Hmm, no you should be getting the 3.x branch of MarqueeLabel which supports/requires Swift 3. I'm not sure why Cocoapods would be installing an older version, plus there's a 2.7.10 bugfix release and a 2.8 branch. I'll check what I can on my end later today.

**Comment by Grimbode** [comment]
I went ahead and did it via line command and it installed the right version. I have no idea why the app would install the 2.7.9 version.

**Comment by cbpowell** [comment]
Weird, I haven't tried the Cocoapods app but maybe I'll play around with it. I guess comparing the app-generated Podfile vs. your "manual" one would be the way to investigate? As far as I can tell, the app just generates the file for you but everything works like normal in the background.

**Comment by cbpowell** [comment]
I'll go ahead and close this one - still not sure why the app was doing that.
