### ISSUE TITLE
Scrolldirection continuous from right to left (arabic)

### ISSUE THREAD

**Issue by ServusJon** [cbpowell/MarqueeLabel#170]
I would like to use the direction option: .continuous
But for arabic user I would to make it scroll continuously from right to left. 
How can I achieve this?

**Comment by cbpowell** [comment]
You can use the `.continuousReverse` type, which is the same as `.continuous` but scrolls in the opposite direction (scroll direction is right). It's intended for right-to-left languages. I haven't tested it much with actual right-to-left languages, but you can see an example in the demo using English. Keep in mind the leading and trailing buffers also "flip" - the leading edge is always on the side that faces the direction of scroll (i.e. the edge that animates out of frame first).
