### ISSUE TITLE
MarqueeLabel to UIViewController title

### ISSUE THREAD

**Issue by OuSS-90** [cbpowell/MarqueeLabel#171]
How to add MarqueeLabel to title of UIViewController ?

**Comment by cbpowell** [comment]
I'm assuming you mean to a `UINavigationBar` of a view controller - check out [the docs on `UINavigationBar` customization](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/UIKitUICatalog/UINavigationBar.html#//apple_ref/doc/uid/TP40012857-UINavigationBar), and in particular the usage of [`UINavigationItem`](https://developer.apple.com/reference/uikit/uinavigationitem) which allows you to set a custom [`titleView`](https://developer.apple.com/reference/uikit/uinavigationitem/1624935-titleview). You can add a MarqueeLabel to a custom title view.

Hope this helps!
