### ISSUE TITLE
failed to update auto layout status

### ISSUE THREAD

**Issue by webMing** [cbpowell/MarqueeLabel#172]
when I  custom class as MarqueeLabel  in inspector , it show an error  : failed to update auto layout status: dlopen (xxx.app) no suitable image found. Did found xxx.app mach-o,but wrong architecture.

when I  remove the IB_DESIGNABLE ，it works  well , wants to know why .

**Comment by cbpowell** [comment]
IBDesignables seem to cause issues sometimes, although I don't recall seeing your specific issue. Take a look at issue #165, specifically [this post](https://github.com/cbpowell/MarqueeLabel/issues/165#issuecomment-255600741), and see if any of that fixes your issue?

**Comment by webMing** [comment]
thank you. tomorrow  l  give it  a  try.

**Comment by webMing** [comment]
it works for me

**Comment by cbpowell** [comment]
Great! Glad it worked.
