### ISSUE TITLE
Possible idea and a question

### ISSUE THREAD

**Issue by daviddelmonte** [cbpowell/MarqueeLabel#178]
Charles, first thanks again for your work on Marquee Label.

Two ideas. 

1. I really could use a scroll once (or twice) capability. I don't have touch access to the label, and continuous scroll is a bit annoying.

2. Is there a version for macOS? If not,  is this possible?

**Comment by cbpowell** [comment]
Glad you find it useful!

For your first question, that is actually possible today. You can set [`holdScrolling = true` ](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L99-L119), which prevents automatic scrolling, and then you can call [`triggerScrollStart`](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L1262-L1280) to programmatically kick off a scroll cycle. As long as you don't change `holdScrolling`, the label will not automatically start again after the triggered scroll completes. If you wanted more than one scroll, could also subclass MarqueeLabel and override the [`labelReturnedToHome`](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L1397-L1411) function to keep track of the number of scrolls.

As for on macOS, I'm less familiar with doing UI stuff _without_ UIKit, but I'm sure it's possible. A lot of the layout calculations would probably transfer from this iOS version.
