### ISSUE TITLE
Impossible to use Swift version in iOS Framework

### ISSUE THREAD

**Issue by Dschee** [cbpowell/MarqueeLabel#181]
Hello guys,

I just happened to add Carthage support for https://github.com/Daltron/NotificationBanner but ran into a problem: The project includes the Swift variant of this library, so I added the Swift library via Carthage, too. The problem is that the `import` statement when using Carthage looks like this:

```Swift
import MarqueeLabelSwift
```

While the import of the Swift framework via CocoaPods still looks like the one in Objective C:

```Swift
import MarqueeLabel
```

Could you please fix this issue in a way that this library can be referred to in another library that supports both CocoaPods AND Carthage? I think the easiest solution would be to rename the Swift framework to be included when using CocoaPods: Just name it `MarqueeLabelSwift` also and all should be fine.

Thanks in advance for your help!

**Comment by Dschee** [comment]
Also note that your minimum iOS version is 9.3 for the Swift framework. I'm not sure if this is intentional but I'm guessing that it's not. It would be great if you could specify 8.0 (which is the minimum version requirement for dynamic frameworks) so we can use it in 9.0, too as an example.

**Comment by cbpowell** [comment]
Actually in Cocoapods you would "select" the Swift version using `pod 'MarqueeLabel/Swift'`, per the readme. That specifies the Swift subspec of [the podspec](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.podspec#L22) (although true, the Objective-C is still the default if you do not specify a subspec).

So I totally haven't tried all these permutations lately, but I believe you can import Obj-C or Swift with Cocoapods OR Carthage using the methods in the below table? Asking for your feedback here, particularly on the Carthage side since I don't use it much, does any one of these definitely NOT work?

 Language | Cocoapods | Carthage
--|------------|----------
Objective-C | `pod MarqueeLabel`  + `#import "MarqueeLabel.h"`| `github "cbpowell/MarqueeLabel"` + `#import <MarqueeLabel.h>`
Swift | `pod MarqueeLabel/Swift` + (no specific import required) | `github "cbpowell/MarqueeLabel"` + `import MarqueeLabelSwift`

(There's also the tvOS version, but I left that out for simplicity)

**Comment by Dschee** [comment]
Hi @cbpowell and sorry for letting you wait so long for an answer. I think I failed in explaining the issue well enough because you clearly misunderstood me. The thing is, that this library works in Apps via both CocoaPods and Carthage. But my goal **was not** to include it into an _app_, instead I tried to include it **into a framework**, namely into [NotificationBanner](https://github.com/Daltron/NotificationBanner).

The difference is: The frameworks, of course, also tries to be available to apps via both Carthage and CocoaPods. Now what THEY did before was to simply include this library via CocoaPods like this: `pod MarqueeLabel/Swift`. And as they were using the dynamic frameworks support in CocoaPods they needed to add `import MarqueeLabel` into their code.

Now that I added Carthage support the problem was that the `import` statement changed to `import MarqueeLabelSwift`. This doesn't compile any more for CocoaPods users (at least I don't think so) so I created this issue to get the `import` names of the Swift libraries alines in both CocoaPods and Carthage installation ways.

I hope this explains this issue.

Of course, maybe there's also a different way of fixing this, but what I need is a solution to support both CocoaPods and Carthage in framework projects when including this library. Feel free to checkout [my PR](https://github.com/Daltron/NotificationBanner/pull/5) there which adds support for Carthage in that project. It works perfectly fine via Carthage with my changes, but my best guess is that it's going to break the framework for CocoaPods users.

**Comment by cbpowell** [comment]
Ah, understood! Yeah I totally missed that, but I see what you mean now.

I'll have to think about it and try a few things - the simplest approach of renaming might have more impacts to Cocoapods users than I'd prefer. It's unfortunate that Carthage doesn't seem to support building only specific targets/frameworks, and they seem against adding that functionality.

I haven't had a chance to try it, but I think Carthage does add an environment variable to the build letting you know it's being built with Carthage? I'm thinking that could be used in a macro of sorts to switch the `import` statement. Not the cleanest, I know, but also not too much impact.

**Comment by cbpowell** [comment]
@Dschee @Daltron So I don't see a great way around this that doesn't cause headaches for current MarqueeLabel users and/or myself. I could:

1. Split the podspec into two separate specs, one for Obj-C and one for Swift (ironically that's how it used to be). However I pretty much consider Swift to be "the future" so I'd actually be inclined to make the Swift version have the base "MarqueeLabel" name. The downside is this would drive a major version number change for naming only, and I don't think I want to do that right now.

2. Create a podspec called `MarqueeLabelSwift` that's basically only for people who need Cocoapods+Carthage compatibility in their released frameworks. This wouldn't be too hard, and it would basically only have an impact on me - I'd just need to keep that separate spec also up to date when releasing new versions. Or this new spec could pull MarqueeLabel/Swift without a version specified, thereby always getting the latest version (pro: no additional maintenance work for me).

Alternatively, people using this framework can work around the issue with a fairly small change. See [my pull request](https://github.com/Dschee/NotificationBanner/pull/1) to @Dschee's branch which would be a quick/immediate fix. It works by adding a `CARTHAGE_CONFIG` custom Swift complier flag, and the revised code then checks if that flag is set when making the import statement. It feels a little clunky, but there's actually an [accepted Swift proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0075-import-test.md) in work to allow checking of module availability which would make it a little cleaner in the future.

What do you guys think?

**Comment by cbpowell** [comment]
I've added a [note to the README](https://github.com/cbpowell/MarqueeLabel/blob/master/README.mdown#swiftframeworkusage) about this topic, so I'll go ahead and close this - BUT, I'm going to keep in in mind for the future because I don't think this is the optimum solution.
