### ISSUE TITLE
Minimum Version Requirement 9.3

### ISSUE THREAD

**Issue by Dschee** [cbpowell/MarqueeLabel#182]
The minimum iOS version is requirement is 9.3 for the Swift framework. I'm not sure if this is intentional but I'm guessing that it's not. It would be great if you could specify 8.0 (which is the minimum version requirement for dynamic frameworks) so we can use it in 9.0, too as an example.

**Comment by cbpowell** [comment]
Yep definitely unintended - thanks! Fixed in [release 3.0.4](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.0.4).
