### ISSUE TITLE
Not Working with TableView

### ISSUE THREAD

**Issue by pinkal** [cbpowell/MarqueeLabel#183]
MarequeeLabel not working with uitableview. It scroll's first time, when we scroll the tableview then it stops scrolling.

**Comment by cbpowell** [comment]
See [this section in the README](https://github.com/cbpowell/MarqueeLabel#use-in-uitableview-and-uicollectionview).

MarqueeLabel can't always know when your table cell scrolls onto the screen, so it can't automatically restart the scrolling animation. You'll need to manually trigger the scroll when the cell appears onscreen.

Please reply back if this does't fix your implementation!

**Comment by pinkal** [comment]
Thank you for quick reply, it is now working by restartlabel in willdisplaycell method.

Thank you.
