### ISSUE TITLE
Prevent backwards scrolling when reaching the end when using .leftToRight type

### ISSUE THREAD

**Issue by Daltron** [cbpowell/MarqueeLabel#185]
### Please follow the general troubleshooting steps first:

- [x] Updated to latest version of MarqueeLabel
- [x] Read the README, in particular the [Special Notes](https://github.com/cbpowell/MarqueeLabel#special-notes)
- [x] For general questions about using MarqueeLabel, post on StackOverflow with the [#MarqueeLabel tag](http://stackoverflow.com/questions/tagged/marqueelabel)

### Usage Details
  - Language: Swift
  - Platform: iPhone/iPad

Hi @cbpowell! 😄  First off, great library, I'm using it in one of my own [NotificationBanner](https://github.com/Daltron/NotificationBanner). I have looked over the source code up and down and there doesn't appear to be a prebuilt way to prevent a label from scrolling back to the beginning when it reaches the end without doing some custom logic myself when using the `.leftToRight` type.  Please correct me if I am wrong.

Thanks!

**Comment by cbpowell** [comment]
Hey @Daltron -- thanks, glad you find it useful!

And yes, you're unfortunately correct - there's no built in way to stop at the end/"away" position, at least not with the base code. MarqueeLabel uses a single continuous keyframe animation for the entire scroll loop, so the animation doesn't actually end until it's scrolled back "home" and therefore not really giving you a good point to hook in at the away position.

The easiest workaround would maybe be to look at the [key times](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L993-L1004) and determine when the label will be at the point you want, and fire a timer to pause the label. That just feels pretty risky for edge cases and gotchas, though.

Your post did make me think of some ideas on how MarqueeLabel could be a little more flexible, so I've created issue #186 to track that. I'll go ahead and close this issue for now, but I want to try and leverage some features of Swift to make what you'd like to do a little easier.

**Comment by Daltron** [comment]
@cbpowell Thanks for the quick reply! I'll see what I can come up with in the meantime! 😄

**Comment by cbpowell** [comment]
Yeah definitely! Feel free to discuss here still if you have any thoughts/questions. It might be cleanest to create your own `.left` type, starting with the code that defines the `.leftRight` type and modify it so that the animation stops at the away point. Note that you'll need to keep the animation around since the backing layer doesn't actually change positions.
