### ISSUE TITLE
One marquee, multiple labels, recognizing taps for each label

### ISSUE THREAD

**Issue by ElSifi** [cbpowell/MarqueeLabel#189]
Hello,

I have something like a news list, that will be displayed in a marquee and I need to recognize taps for each title
Is there a way to achieve that behavior?

**Comment by iDevelopper** [comment]
What about a table view?

**Comment by ElSifi** [comment]
Thanks for replying, iDevelopper

Can you explain more? I need all the news to be in one marquee, not multiple marquees

I'm thinking now of using an AtributedString (NSLinkAttributeName) to detect the tap on each different news title

**Comment by ElSifi** [comment]
I ended up using an auto-scrolling horizontal UICollectionView.

**Comment by iDevelopper** [comment]
Good idea! With a timer?

**Comment by ElSifi** [comment]
Yes, exactly. works just fine in my case.

**Comment by cbpowell** [comment]
Good alternative!
