### ISSUE TITLE
Unable to change font size in MarqueeLabel

### ISSUE THREAD

**Issue by d99101** [cbpowell/MarqueeLabel#19]
Hi Charles,

Thanks for the awesome marquee label!

I am having problems changing the Marquee label font size. I have tried changing the CGRectMake dimension and the font size, but still unable to make the font any larger.

Here is the code, please advise. Thanks in advance!

```
- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {


        MarqueeLabel* continuousLabel = [[MarqueeLabel alloc] initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, 60) rate:60.0f andFadeLength:5.0f];
        continuousLabel.tag = 102;
        continuousLabel.marqueeType = MLContinuous;
        continuousLabel.numberOfLines = 1;
        continuousLabel.opaque = NO;
        continuousLabel.enabled = YES;
        continuousLabel.shadowOffset = CGSizeMake(0.0, -1.0);
        continuousLabel.textAlignment = UITextAlignmentCenter;
        continuousLabel.textColor = [UIColor colorWithRed: 176.0f/255.0f green:176.0f/255.0f blue:176.0f/255.0f alpha:1.0];
        continuousLabel.backgroundColor = [UIColor clearColor];
        continuousLabel.font = [UIFont fontWithName:@"Cochin Bold" size:20.0];
        continuousLabel.text= @"Label Title";


        [self.view addSubview:continuousLabel];
    }
}
```

**Comment by divyeshdobariya** [comment]
Unable to change font size, Is there any update ? I tries so many thing but not change the size of the font 

Here is the code , please look at 

`let main_lblVideoTitle = MarqueeLabel()
        main_lblVideoTitle.frame = CGRect(x: frontSpacing, y: topHeight + playerHeight + sliderHeight + labelSpacing, width: SCREEN_WIDTH - (frontSpacing*2), height: labelHeight)
        main_lblVideoTitle.fadeLength = 50
        main_lblVideoTitle.speed = .rate(30.0)
        main_lblVideoTitle.textColor = .white
        main_lblVideoTitle.font = UIFont.boldSystemFont(ofSize: 30.0)
        mainPlayerView.addSubview(main_lblVideoTitle)`

is there any solution ?
Thanks
