### ISSUE TITLE
awayFromHome always returns false

### ISSUE THREAD

**Issue by LucasKovacs** [cbpowell/MarqueeLabel#190]
### Usage Details
  - Language: Swift
  - Platform: iPhone
  - iOS Version: iOS 8.4
  
### Expected Behavior
Should return something different than false when the label is scrolling

### Actual Behavior
Always returns false, when the label is scrolling, and when is not too.

### Steps to Reproduce the Problem
1. Simple create a marqueelabel and make it scroll.
2. print awayFromHome value

**Comment by cbpowell** [comment]
This appears to work on the iOS 8.4 simulator (using Xcode 9.0 beta 2) in the demo project, with the following setup:

```swift
@objc func awayStatus() {
    print(self.demoLabel1.awayFromHome)
}

override func viewDidLoad() {
    super.viewDidLoad()
        
    // Continuous Type
    demoLabel1.tag = 101
    demoLabel1.type = .continuous
    demoLabel1.animationCurve = .easeInOut

    let _ = Timer.scheduledTimer(timeInterval: 0.2, target: self, selector: #selector(awayStatus), userInfo: nil, repeats: true)

    // …

```

I get `true` when the label is away, and `false` when home - maybe theres something specific to your usage that causing the problem?

The method by which MarqueeLabel gets the away status should work all the way back to iOS 2.0 (in theory). It compares the position of the animating `presentationLayer` to the model layer, and if they don't match declares the label to be away from home.

**Comment by LucasKovacs** [comment]
Thanks for your reply. It seems to be working. My mistake was that I wasn't using a timer. I was expecting to get that value just by calling awayFromHome.

**Comment by cbpowell** [comment]
No problem! Although I just used the timer to call the `awayFromHome` function every 0.2 seconds, basically to make sure it was working as I expected. The `awayFromHome` function only returns the away status at the time of call to the function - it doesn't do any asynchronous callbacks or anything.

If you're trying to do other things just as the label leaves from or returns to the home position, it might be easier (than managing a timer) to subclass MarqueeLabel and override the [`labelWillBeginScroll()`](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L1338) and [`labelReturnedToHome()`](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L1354) functions with your own implementations that call/trigger something else.
