### ISSUE TITLE
Forward contentMode property to sublabel

### ISSUE THREAD

**Issue by FlaviaBondJamesBondsHusband** [cbpowell/MarqueeLabel#191]
### Please follow the general troubleshooting steps first:

- [x] Updated to latest version of MarqueeLabel
- [x] Read the README, in particular the [Special Notes](https://github.com/cbpowell/MarqueeLabel#special-notes)
- [x] For general questions about using MarqueeLabel, post on StackOverflow with the [#MarqueeLabel tag](http://stackoverflow.com/questions/tagged/marqueelabel)

### Usage Details
  - Language: Swift
  - Platform: AppleTV
  - iOS Version:  tvOS 10.2
  
Not really sure where feature requests are supposed to go so I'm posting it here.

In the function `forwardPropertiesToSublabel()`, could you add the key **"contentMode"** please. When a label is centred and you are toggling the `labelize` variable, the text alignment quickly snaps to the contentMode side - usually set to left - before animating back to the centre. Adding this property fixes the issue.

**Comment by cbpowell** [comment]
Sure - in my testing with the demo project I don't see any issues as a result of adding that property.

To better understand the issue you're seeing (having not experienced myself): are you talking about a center text alignment, non-scrolling label (i.e. short enough to display everything) that is then labelized?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Yes, sorry I wasn't very clear. 

I have a Marquee Label setup on a UICollectionViewCell on tvOS. The label has centre alligned text. When the cell is focused, the Marquee Label's constraints are updated to reflect the cell's focused image size. The `labelize` variable is also set to `false` when this happens. This whole process is animated alongside the focus animation. When the **"contentMode"** property is left as default (**Left**), the text snaps to the left and then animates back to the centre in a weird looking animation. This also happens during the unfocused animation when the `labelize` variable is set to true and the width constraints updated. Setting this property to **"Centre"**, fixes the weird animation.

**Comment by cbpowell** [comment]
Ah thanks for the info. I'll add in `contentMode` as a forwarded property and as a pass-through (i.e. create setters/getters) in release 3.1.1 shortly.

(Side note: I tried to `lint` the 3.1.1 release in Cocoapods last night but got a few errors. It might be related to the Xcode beta so I'll have to work that out today before I can push the release)

**Comment by cbpowell** [comment]
Added this in [Release 3.1.1](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.1.1) - thanks!
