### ISSUE TITLE
@IBInspectable default values in Storyboard not set (for Swift).

### ISSUE THREAD

**Issue by iDevelopper** [cbpowell/MarqueeLabel#193]
### Please follow the general troubleshooting steps first:

- [x] Updated to latest version of MarqueeLabel
- [x] Read the README, in particular the [Special Notes](https://github.com/cbpowell/MarqueeLabel#special-notes)
- [x] For general questions about using MarqueeLabel, post on StackOverflow with the [#MarqueeLabel tag](http://stackoverflow.com/questions/tagged/marqueelabel)

### Usage Details
  - Language: Swift
  - Platform: iPhone / iPad, iOS
  - iOS Version: 10.3
  
### Expected Behavior
Default values shown in storyboard.

### Actual Behavior
Not shown, instead we can see --

### Steps to Reproduce the Problem
  1. Create a new Swift Project.
  2. run pod init.
  3. open podfile:

platform :ios, '9.0'
target 'MarqueeLabelTest' do
  use_frameworks!

  pod 'MarqueeLabel/Swift'

end

  4. run pod install.
  5. open the project xworkspace file.
  6. in storyboard add a label to the view controller and rename its custom class to MarqueeLabel.

**Comment by cbpowell** [comment]
After a little research, this seems like a shortcoming of Xcode. Xcode doesn't pull the default values into the IB fields, even though they are [set in code]().

There would appear to be [ways to workaround it](https://www.reddit.com/r/iOSProgramming/comments/5tutt5/ib_is_ignoring_default_values_defined_in/) and get the fields populated, but I'm not a fan of the extra code and duplication. So at this point I guess I'll close the issue, and hope eventually Xcode adds it as a feature!
