### ISSUE TITLE
Error "internal protection" when using with cocoapods (Swift)

### ISSUE THREAD

**Issue by skrew** [cbpowell/MarqueeLabel#194]
### Please follow the general troubleshooting steps first:

- [x ] Updated to latest version of MarqueeLabel
- [x ] Read the README, in particular the [Special Notes](https://github.com/cbpowell/MarqueeLabel#special-notes)

### Usage Details
  - Language: Swift 3
  - Platform: iOS 
  
While the demo works, some functions like `controllerLabelsAnimate` or  `controllerViewDidAppear` won't compile in my project with MarqueeLabel/Swift installed with Cocoapods. EG: 
`'controllerLabelsAnimate' is inaccessible due to 'internal' protection level`

Declaring functions with "public" works, but i don't know if it's the correct way to fix.

**Comment by cbpowell** [comment]
Whoops, yeah those functions are completely missing access levels. I'll change them to `open` level - thanks for the heads up!

**Comment by cbpowell** [comment]
Fixed this (hopefully didn't miss something) in [Release 3.1.2](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.1.2), thanks!
