### ISSUE TITLE
Scroll short text <Objective C>

### ISSUE THREAD

**Issue by quocan2812** [cbpowell/MarqueeLabel#195]
Sorry about this issues, I apply marrqueeLabel in Obj C and it works well with long text, but with short text, it don't automatic scroll, 
I try to find it for a long time 
Pls help me, can I set property to scroll with short text ^^

**Comment by cbpowell** [comment]
Hi @quocan2812! Automatic scrolling with short text lengths (when the entire text fits within the frame of the label view) is not a feature of MarqueeLabel. MarqueeLabel tries to replicate the scrolling label functionality found in Apple's Music apps, but not the "news ticker" type of effect I think you're looking for.

There are ways to add the functionality you're looking for with some modifications to MarqueeLabel - see [this pull request](https://github.com/cbpowell/MarqueeLabel/pull/148). There are better ways to handle the auto-scrolling news ticker though, like with an infinite-scroll, horizontal collection view. Hope this helps!
