### ISSUE TITLE
How to setup non-stop mode?

### ISSUE THREAD

**Issue by iceman201** [cbpowell/MarqueeLabel#205]
### Please follow the general troubleshooting steps first:

- [x ] Updated to latest version of MarqueeLabel
- [x ] Read the README, in particular the [Special Notes](https://github.com/cbpowell/MarqueeLabel#special-notes)
- [x ] For general questions about using MarqueeLabel, post on StackOverflow with the [#MarqueeLabel tag](http://stackoverflow.com/questions/tagged/marqueelabel)

### Usage Details
  - Language: <Objective-C>
  - Platform: <iPhone>
  - iOS Version: <iOS 11> 
  

### Expected Behavior
The MarqueeLabel has non stop animation feature.

### Actual Behavior
the Label animate the text will stop for few sec every time finish run a loop.

### Steps to Reproduce the Problem
  1. Include all your demo, there is no non-stop feature showing.

**Comment by iceman201** [comment]
I find `restartLabelsOfController` this in description, and I added `[MarqueeLabel restartLabelsOfController:self]; ` still does the same, stop 1 sec after one rolling

**Comment by cbpowell** [comment]
Is your issue that you want the scrolling to _never_ pause at the home position? If so you can try setting the [`animationDelay` property](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L337) to `0.0` and use one of the continuous scrolling types (`.continuous` or `.continuousReverse`).

**Comment by cbpowell** [comment]
Closing this one for now - please reopen if your question isn't answered!
