### ISSUE TITLE
problems with integration

### ISSUE THREAD

**Issue by wolodo** [cbpowell/MarqueeLabel#208]
Hi,
I have problems with integrating MarqueeLabel using pods. 

I am using xcode 9/swift 4

1. my podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bookplayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bookplayer
  pod 'MarqueeLabel/Swift'

end
```

2. pod install, restart xcode...and nothing. Xcode does not know the class MarqueeLabel. However, I am able to set MarqueeLabel custom class in the Ui editor, I can even create outlet of my label with this class. But controller says "Use of undeclared type 'MarqueeLabel'"

What am I doing wrong?

**Comment by wolodo** [comment]
alright...managed to solve it. looks like some bug in xcode. after couple of restarts and xcode cache wipes it started to work. sorry for disturbing

**Comment by cbpowell** [comment]
No problem, glad you got it sorted out!
