### ISSUE TITLE
numberOfLine Shows only 1 line

### ISSUE THREAD

**Issue by jayb611** [cbpowell/MarqueeLabel#209]
### Please follow the general troubleshooting steps first:

- [ ] Updated to latest version of MarqueeLabel
- [ ] Read the README, in particular the [Special Notes](https://github.com/cbpowell/MarqueeLabel#special-notes)
- [ ] For general questions about using MarqueeLabel, post on StackOverflow with the [#MarqueeLabel tag](http://stackoverflow.com/questions/tagged/marqueelabel)

### Usage Details
  - Language: 
  - Platform: 
  - iOS Version:  
  

### Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by cbpowell** [comment]
By design, MarqueeLabel [keeps the `numberOfLines` property equal to 1](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L1499-L1508), and can display only one line of text.
