### ISSUE TITLE
superview is keyWindow ,can't scroll

### ISSUE THREAD

**Issue by U7426** [cbpowell/MarqueeLabel#215]

**Comment by U7426** [comment]
like this：
[view1 addSubview:marqueeLabel];
[[UIApplication sharedApplication].keyWindow addSubview:view1];

marqueeLabel is not working

**Comment by cbpowell** [comment]
Might be because the methods MarqueeLabel uses to detect when it’s onscreen are failing when the super view is made key. Not sure why offhand, but generally that means you’ll need to manually trigger the scroll start.

**Comment by U7426** [comment]
Which method I need

**Comment by U7426** [comment]
Which method I need， "restartLabel" that is still invalid.

**Comment by cbpowell** [comment]
Try the `triggerScrollStart` method, which should start the scrolling animation IF all other conditions for scrolling are met. The primary condition being your text does not fit within the bounds of the view.

**Comment by laoyur** [comment]
@cbpowell hi, I called `triggerScrollStart`, but it does not work.

**Comment by cbpowell** [comment]
I should have included that you need to use `triggerScrollStart` when you're confident the window/view is loaded and onscreen. I expect that it wouldn't work if used immediately after the line where you add the view to your key window. Typically you might call `triggerScrollStart` in the `viewDidAppear` method of your view controller.

**Comment by cbpowell** [comment]
@U7426 @laoyur did using `triggerScrollStart` or `restartLabel` when you know the label view is **on screen** fix your issue?

MarqueeLabel uses UIKit animations, which will fail if the view is not loaded yet. If you tried the above and still didn't have any success, can you post more of your implementation code?

**Comment by cbpowell** [comment]
Going to consider this closed/solved given the lack of responses, please respond if my explanations above didn't solve it for you!
