### ISSUE TITLE
Compiler won't recognize MarqueeLabel class in ViewController when installed via Pods

### ISSUE THREAD

**Issue by aqeelaslam** [cbpowell/MarqueeLabel#218]
### Usage Details

  - Language: Swift
  - Platform: iPhone/iPad
  - iOS Version: 11.2 
  

I added the pod in my podfile and installed the pod. Then I went to my storyboard, I could assign the MarqueeLabel class to the UI Label. 

### Expected Behavior

I come to write in the controller class to set the text of the label and it works fine.

### Actual Behavior

The compiler doesn't recognize MarqueeLabel as a valid data type. 

There isn't any `import <moduleName>` directive in the ReadMe as well.

I try `import MarqueeLabel` but that isn't any module. 

Am I missing anything here ?

### Steps to Reproduce the Problem
  1. add `pod 'MarqueeLabel/Swift'` in podfile
  2. Give a UI Label in Storyboard `MarqueeLabel` class 
  3. Change to ViewController to set the text of this label

**Comment by cbpowell** [comment]
Hmm, it sounds like you're doing everything right? But just to make sure since you're using Cocoapods, did you:
1. Run `pod install` after adding the MarqueeLabel line to your pod file?
2. Open the .xcworkspace file that Cocoapods creates? If you open the original .xcproject file, you will get a `No such module 'MarqueeLabel'` error.

**Comment by aqeelaslam** [comment]
Yes Sir, I mean autocomplete by XCode. 

I've since removed the Pod, saving the `MarqueeLabel.swift` class before doing that. And now am using it as a resource in my project. No Pods and nothing. 

And it's working fine.

**Comment by cbpowell** [comment]
Yeah it seems like a Cocoapods problem, and I'm not sure what your fix is unfortunately.

I guess make sure your Cocoapods gem is up to date, then try putting `use_frameworks!` at the top of your Podfile (if you didn't have it before), and then maybe try with an empty, new Xcode project and see if it works as expected there?

I haven't tried making a new Xcode test project myself, but I did build my existing MarqueeLabel+Cocoapods test project in Xcode 10 and it was successful.

**Comment by cbpowell** [comment]
@aqeelaslam Did you figure this one out? Or did you end up just using the class file?

**Comment by aqeelaslam** [comment]
I'm still using the class file Charles.

**Comment by lukelucas247** [comment]
I solved this by using:

https://github.com/CocoaPods/cocoapods-deintegrate

...to deintegrate all pods, I then removed the workspace and then did a fresh pod install. 

I did reinstall using the current pre-release version of cocoapods, not sure if this made a difference or not.

**Comment by cbpowell** [comment]
@lukelucas247 thanks for the info! I'll go ahead and close this one, I'm not aware of anything I can do with the MarqueeLabel podspec to help - but let me know if you guys find something that I can change to help!
