### ISSUE TITLE
Don't break animation in table cell when reloadData is called.

### ISSUE THREAD

**Issue by alexejn** [cbpowell/MarqueeLabel#219]
There is some trouble with MarqueeLabel in cell. I have table to show stock tickers and their prices. In case ticker name is too long i use Marquee label. Every 3 seconds i update prices, dates and other labels  in cells with reloadData. When i do it the marquee label animation stopped (animationDidEnd called). So behavior i want to achive is on every reloadData for visible cell if name of ticker is same (i don't update it ), and animation is processing, then keep animation, don't restart it. How can i do it? Thanks.

**Comment by cbpowell** [comment]
I _think_ calling `reloadData` effectively recreates the UITableViewCell views, which means iOS is either a) creating a new cell view with a new MarqueeLabel instance (meaning the animation will start fresh), or b) reusing a cell view that may or may not be the same cell at that position, and therefore might get set to a new text value (which will start the animation with the new text).

Regardless, if you are setting only the ticker name to your MarqueeLabel instances, and you set it to the same value it already has, MarqueeLabel will not interrupt the animation. You can see that's the case in the [setter for the `text` property here](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L1388-L1390), in that if the `newValue` matches the current value the setter simply returns.

It sounds like `reloadData` is wiping out your cells, which MarqueeLabel can't help you with. You'll probably need to develop a way to update only the appropriate information in the on-screen cells without fully reloading them. I'd suggest looking into UITableView's `indexPathsForVisibleRows` to get the on-screen cells, and then update the fields in that subset.

Hope this helps!
