### ISSUE TITLE
MarqueeLabel can not begin scrolling when back from other view controller.

### ISSUE THREAD

**Issue by wanglichun** [cbpowell/MarqueeLabel#222]
1、in viewcontroller A,  add a marqueelabel on its view，the label begin scrolling;
2、then push to viewcontroller B from viewcontroller A;
3、then back to viewcontroller A from viewcontroller B by swap very quickly on left edge, the marqueelabel just do not begin scrolling.
4、but back to viewcontroller A from viewcontroller B by click back button, the marqueelabel begin scrolling normally.

the problem happen before 11.0 operation system, I can not find the reason.

**Comment by cbpowell** [comment]
This can happen when MarqueeLabel doesn't automatically get notification of view controller changes - see the solution in issue #206 as a workaround.

Hope this helps!
