### ISSUE TITLE
Swift 4.2 Branch?

### ISSUE THREAD

**Issue by daviddelmonte** [cbpowell/MarqueeLabel#223]
Hi there, any chance of a 4.2 branch or workaround? I get compile errors when I try to add MarqueeLabel.swift to a new -- 4.2 project.

Many thanks

**Comment by cbpowell** [comment]
Looks like it was just some minor changes - see the [swift-4.2 branch](https://github.com/cbpowell/MarqueeLabel/tree/swift-4.2)

**Comment by daviddelmonte** [comment]
Brilliant - thanks!

**Comment by Daltron** [comment]
@cbpowell Any chance we can get a new CocoaPods release for Swift 4.2? 😄  I'm blocked from pushing a new release until MarqueeLabel can be compiled to Swift 4.2.

**Comment by cbpowell** [comment]
@Daltron I'm totally blanking on if it actually works without it in front of me, but there's got to be a way to tell Xcode to compile the current MarqueeLabel with Swift 4.1? Something like this: https://github.com/CocoaPods/CocoaPods/issues/6791#issuecomment-331529774

Won't be able to make a new release until later tonight, so hopefully this can work in the interim?

**Comment by Daltron** [comment]
@cbpowell Thanks for the quick response! Unfortunately, I think that only pertains to your Podfile within your project. I haven't successfully found a way to support multiple swift versions if your pod depends on other pods. I think the problem stems from the `.swift-version` file which tells CocoaPods what to compile your project it.

**Comment by cbpowell** [comment]
Ah good point, I forgot you use it as a dependency. I'd bet that `post_install` script could be modified to work from your podspec, but no clue what exactly needs to change and that's kind of a bad workaround anyway.

Well I'm totally cool with bumping it to Swift 4.2, no reason to support older Swift versions in my opinion...but unfortunately I won't be able to get to it until tonight!

**Comment by Daltron** [comment]
@cbpowell No problem at all, I'll patiently wait! Thanks again!

**Comment by cbpowell** [comment]
Just pushed [release 3.2.0](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.2.0) - let me know if you have any issues!

**Comment by daviddelmonte** [comment]
Thanks Charles. No issues in my projects.

**Comment by Daltron** [comment]
@cbpowell Thanks for the quick release, it's greatly appreciated!
