### ISSUE TITLE
No way to keep number of lines with labelize enabled?

### ISSUE THREAD

**Issue by CokePokes** [cbpowell/MarqueeLabel#224]
### Usage Details
  - Language:  Objective-C
  - Platform:  iPhone/iPad
  - iOS Version:  11.3 
  

### Expected Behavior

Want to keep number of lines before tapping to scroll.

### Actual Behavior

 Number of lines becomes one, even with labelize enabled

**Comment by cbpowell** [comment]
Hi @CokePokes - I've designed MarqueeLabel around the assumption that it will contain a single line of text, so there's no built-in way to switch between multiple and single lines of text.

If it's critical to your usage, you could probably work around it by having two labels at the same position: one regular, multi-line UILabel, and one MarqueeLabel. Set the same text string to both, but set the MarqueeLabel to hidden to start (or alpha zero). When the user taps, set the regular, multi-line UILabel to hidden and unhide the MarqueeLabel.

Hope this helps!

**Comment by CokePokes** [comment]
Thanks! I ended up doing this a few minutes before you replied. I was a little confused as the project states it's "a drop-in replacement for UILabel."
