### ISSUE TITLE
Long Arabic texts are not shown

### ISSUE THREAD

**Issue by furkanhatipoglu** [cbpowell/MarqueeLabel#225]
### Usage Details
  - Language: Swift
  - Platform: Apple Tv/tvos
  
### Expected Behavior
I expect that there should be text on the label.

### Actual Behavior
There is no problem with short Arabic texts but long Arabic texts are not shown on label.

### Steps to Reproduce the Problem
  1. Give the text :
//            "في فسقط فهرست الأسيوي عرض, مشروط استراليا، لها ما. ليبين الأوضاع ومحاولة لم كلا, وسمّيت وانتهاءً التاريخ، دنو عن. أحدث تطوير الأولى حيث عن. تم بداية الثالث ذلك, أم يبق لغات واتّجه. عدم القادة لإعلان مكثّفة كل, الدول وقدّموا ان دول, لمّ في وسوء ممثّلة الإثنان.ة ما, من فعل أسابيع استمرار, و كما انتهت بالحرب الأوربيين. ٣٠ أراض مشارف عرض, ومن أمدها إحتار السبب مع, أخذ مشارف وا إذ. جهة مع الأجل انتهت شواطيء, مكن عن أمدها فاتّبع, ٢٠٠٤ وأزيز المب. بداية الثالث ذلك, أم يبق لغات واتّجه. عدم القادة لإعلان مكثّفة كل, الدول وقدّموا ان دول, لمّ في وسوء ممثّلة الإثنان.ة ما, من فعل أسابيع استمرار, و كما انتهت بالحرب الأوربيين. ٣٠ أراض مشارف عرض, ومن أمدها إحتار السبب مع, أخذ مشارف وا إذ. جهة مع الأجل انتهت شواطيء, مكن عن أمدها فاتّبع, ٢٠٠٤ وأزيز المب. بداية الثالث ذلك, أم يبق لغات واتّجه. عدم القادة لإعلان مكثّفة كل, الدول وقدّموا ان دول, لمّ في وسوء ممثّلة الإثنان.ة ما, من فعل أسابيع استمرار, و كما انتهت بالحرب الأوربيين. ٣٠ أراض مشارف عرض, ومن أمدها إحتار السبب مع, أخذ مشارف وا إذ. جهة مع الأجل انتهت شواطيء, مكن عن أمدها فاتّبع, ٢٠٠٤ وأزيز المب. بداية الثالث ذلك, أم يبق لغات واتّجه. عدم القادة لإعلان مكثّفة كل, الدول وقدّموا ان دول, لمّ في وسوء ممثّلة الإثنان.ة ما, من فعل أسابيع استمرار, و كما انتهت بالحرب الأوربيين. ٣٠ أراض مشارف عرض, ومن أمدها إحتار السبب مع, أخذ مشارف وا إذ. جهة مع الأجل انتهت شواطيء, مكن عن أمدها فاتّبع, ٢٠٠٤ وأزيز المب."

**Comment by cbpowell** [comment]
Can you try that same string in a regular UILabel? Unfortunately the UILabel class has an upper limit on the length of text, and if that length is exceeded the label will appear blank. I explained it in a little more length [in this issue](https://github.com/cbpowell/MarqueeLabel/issues/220#issuecomment-406305961).

MarqueeLabel enforces a size limit to try and prevent the disappearing text issue, but the limit might actually be different for Arabic text. If the text appears blank with a regular UILabel, that's the issue.

**Comment by furkanhatipoglu** [comment]
There is no problem with regular UILabel, even I gave the arabic text 4 times longer.

**Comment by cbpowell** [comment]
Interesting, thanks for checking! I’ll take a look into it this weekend.

**Comment by cbpowell** [comment]
That string works fine in the basic test label I set up. Can you provide more details about how you are configuring your label?

**Comment by furkanhatipoglu** [comment]
Here is my set up.

   let rssMarqueeLabel = MarqueeLabel()
 
    func setRSSFeedLabel () {

        rssMarqueeLabel.frame = CGRect(x: 0, y: pageScrollView.bounds.maxY - 50, width: pageScrollView.bounds.width, height: 50)
        rssMarqueeLabel.backgroundColor = UIColor.customColors.marqueeBackgroundColor
        rssMarqueeLabel.textColor = UIColor.white
        rssMarqueeLabel.type = .continuousReverse
        rssMarqueeLabel.textAlignment = .right
        rssMarqueeLabel.animationDelay = 2
        rssMarqueeLabel.speed = .rate(75)
        pageScrollView.addSubview(rssMarqueeLabel)
    }

// After service response, I set text property.
self.rssMarqueeLabel.text =

**Comment by cbpowell** [comment]
Sorry it's taken so long, haven't had a chance to look at this. I haven't been able to replicate this, at least with a basic mockup of an app that copies your setup.

If you haven't already solved this, maybe check your app's general logic related to this label? Make sure it's actually setting the text, is visible, etc.

**Comment by cbpowell** [comment]
Going to close this one due to inactivity and inability to replicate.
