### ISSUE TITLE
Tap to scroll does not work

### ISSUE THREAD

**Issue by minaMagedNaeem** [cbpowell/MarqueeLabel#233]
### Usage Details
  - Language: Swift
  - Platform: iPhone
  
### Expected Behavior
When enabling tap to scroll property, the label should start scrolling when tapped and stopped when tapped

### Actual Behavior
The label does not scroll when tapped

**Comment by daviddelmonte** [comment]
I'm seeing this issue as well. Anyone have workaround?

**Comment by cbpowell** [comment]
Good catch, thanks! Looks like some of the logic had gotten mixed up, as you pointed out. [Release 3.2.1](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.2.1) fixes this issue.
