### ISSUE TITLE
MarqueeLabel crashes when using CocoaPods

### ISSUE THREAD

**Issue by LucasKovacs** [cbpowell/MarqueeLabel#237]
### Usage Details
  - Language: Swift 5
  - Platform: iPhone 6 Plus, tested also on iPhone XR
  - iOS Version: iOS 10.3.1, tested also on iOS 13

### Expected Behavior
Marquee labels work without crashes

### Actual Behavior
App Crashes with error
Thread 1: EXC_BAD_ACCESS (code=2, address=0x10e238370)

### Steps to Reproduce the Problem
I've used CocoaPods to install the package, the process finishes without errors

```
# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SubteVivo
  pod 'MarqueeLabel', '~> 4.0.0'
end
```

Although the first error that I see is a lot of missing MarqueeLabels, to fix the issue I add

`import MarqueeLabel`

After that the app runs, but it crashes. The only way to solve it is moving the MarqueeLabel.swift file to my project, instead of leaving it on the Pods project

**Comment by cbpowell** [comment]
The most common reason for the EXC_BAD_ACCESS errors is when you inadvertently try to use a non-MarqueeLabel object (usually a regular UILabel) like it's a MarqueeLabel object, which can happen when using IB (i.e. [this in the readme](https://github.com/cbpowell/MarqueeLabel#storyboards)).

Check that the Module field is set in IB, which could explain why you're getting a crash using Cocoapods but not with direct import?

**Comment by LucasKovacs** [comment]
Thanks @cbpowell that was the issue. I had to add the MarqueeLabel to the label Module field
