### ISSUE TITLE
Swift Package Manager removed

### ISSUE THREAD

**Issue by cbpowell** [cbpowell/MarqueeLabel#239]
The `Package.swift` file has been temporarily removed, given that SPM hasn't previously worked with iOS and was causing a conflict with Carthage on Xcode 11 (ref #238).

Will be reimplemented at a later time.

**Comment by pcmanik** [comment]
@cbpowell  Hi, is it still broken in Xcode 11? Can you please try integrating SPM now?

**Comment by furiosFast** [comment]
news?

**Comment by cbpowell** [comment]
Merged in the work @rollmind did - let me know if you have any issues actually using it in SPM (I haven't really tried yet!)

**Comment by lvnkmn** [comment]
> Merged in the work @rollmind did - let me know if you have any issues actually using it in SPM (I haven't really tried yet!)

@cbpowell It works for me, looking forward to a release of this.
