### ISSUE TITLE
short text don't scroll

### ISSUE THREAD

**Issue by hien352911** [cbpowell/MarqueeLabel#251]
### Usage Details
  - Language: Swift
  - Platform: iPhone
  - iOS Version: Simulator iOS 13.3
  
### Expected Behavior
 scroll short text

### Actual Behavior
 short text don't scroll: Ex: This is a test of MarqueeLabel

### Steps to Reproduce the Problem

  1. Download sample project from github
  2. Set demoLabel1 from "This is a test of MarqueeLabel, with a somewhat long string." to "This is a test of MarqueeLabel,"
  3. Run simulator iPhone 8, iOS 13.3
  4. MarqueelLabel don't scroll

**Comment by cbpowell** [comment]
Hi! That is actually by design. MarqueeLabel does not scroll if the text will fit inside the given frame.
