### ISSUE TITLE
Deployment target warning in Xcode 12

### ISSUE THREAD

**Issue by cbiggin** [cbpowell/MarqueeLabel#255]
Language: Swift
Platform: iPhone
iOS Version: 14
Xcode version: 12.0 (12A7209)

I'm getting a warning concerning MarqueeLabel when compiling under Xcode 12 (12A7209). I heavily use SPM and MarqueeLabel is a dependency of [NotificationBannerSwift](https://github.com/Daltron/NotificationBanner).

Here is the warning:

<img width="335" alt="Screen Shot 2020-09-24 at 11 14 55 AM" src="https://user-images.githubusercontent.com/66640/94164573-34d1dc80-fe57-11ea-8cb6-62e3cfe6a77f.png">

I have noticed that NotificationBannerSwift dependency is the following:
```
    dependencies: [
        .package(url: "https://github.com/SnapKit/SnapKit", from: "5.0.1"),
        .package(url: "https://github.com/cbpowell/MarqueeLabel", from: "4.0.1")
    ],
```

So it is not _quite_ the latest version.

**Comment by cbpowell** [comment]
Ah yeah the package file still allows down to iOS 8, hence the warning. Can probably drop iOS 8 support in SPM at this point! Thanks for the heads up, I’ll change it soon.
