### ISSUE TITLE
How can I snapshot the changing label

### ISSUE THREAD

**Issue by AbooJan** [cbpowell/MarqueeLabel#257]
### Usage Details
  - Language: Swift
  - Platform: iPhone/iPad
  - iOS Version: all
  
------
I want to create a timer at one second repeat to snapshot the animation change label，but the snapshot image is always the same, it is not the after change label.

then how can I snapshot the changing label?
Thanks~

**Comment by cbpowell** [comment]
Hmm can't say I've ever tried this - are you using something [like this approach](https://www.hackingwithswift.com/example-code/media/how-to-render-a-uiview-to-a-uiimage)?

MarqueeLabel works under the hood with CAKeyframeAnimations, and the scrolling is just an in-flight animation. You would need to use an approach that captures animations as well. Haven't tried it myself, but maybe the method suggested on [this StackOverflow answer](https://stackoverflow.com/questions/25511339/how-to-capture-a-uiview-snapshot-while-animating-images-inside-that-view)?

**Comment by iDevelopper** [comment]
I tested in one of my apps, and this works:
```swift
        if let label = self.stationLabel {
            let renderer = UIGraphicsImageRenderer(size: label.bounds.size)
            let image = renderer.image { ctx in
                label.drawHierarchy(in: label.bounds, afterScreenUpdates: true)
            }
            print(image)
        }
```

**Comment by cbpowell** [comment]
@iDevelopper thanks for testing it out!
