### ISSUE TITLE
Question: How to enable MarqueeLabel on childviewcontroller on mainviewcontroller?

### ISSUE THREAD

**Issue by KamandaK9** [cbpowell/MarqueeLabel#258]
### Usage Details
  - Language:  Swift 
  - Platform:  iPhone 
 
  

Expected Behavior

For the label to autoscroll when long text is show in the label, user initiates this by clicking a long marker on map

Actual Behavior

 Label doesn't scroll when long text is entered from the start, the label is located on a panel drawer that overlaps the mapviewcontroller but no scrolling is enabled, even after forcing it with restartlabel() and scrolling start. 

I've also tested this on a different project where it's on the main view controller and it works perfectly however when I replicate it on the project where the mapviewcontroller loads the childviewcontroller xib it doesn't seem to work at all.

sorry I didn't fill this form out correctly, first time posting on github

**Comment by cbpowell** [comment]
Hmm that's an interesting one - not sure why it wouldn't be working. Have you double checked the easy stuff like making sure the instances in the xib are hooked up right? (i.e. that the instances you're calling `restartLabel` on aren't nil) MarqueeLabel can have trouble detecting the presentation of child view controllers, so it might not scroll automatically.

You can also try setting some breakpoints on the various `return` lines in [this general area](https://github.com/cbpowell/MarqueeLabel/blob/221e384acb3e36149ce2dfb2ad2e51570a9b5095/Sources/MarqueeLabel.swift#L851-L887), to see why the animation is finishing (or terminating early). Keep in mind that early on in the view setup they can get hit a lot and that's harmless, so you'd want to maybe only enable the breakpoint(s) just before the tap in your example.

**Comment by KamandaK9** [comment]
Thank you, I shall give that a go and let you know. I also feel the issue is in the calling of the animation to start, the problem is definitely when the my childviewcontroller shows up, theres a problem there.

**Comment by KamandaK9** [comment]
I tested it on a fresh project with breakpoints and notice that theres no issues with the pod. However on my other project, I put breakpoints and notice that Marquee doesn't even get called at all. Its like it not attached when it comes up. I'm going to try some troubleshoot methods to see if I can crack it. I really like this feature and hope to get it working. Must be a problem on my end with the connection.

**Comment by cbpowell** [comment]
Awesome, you’re welcome, glad you got it fixed!
