### ISSUE TITLE
Can you please update demo to include tableview-> horizontal collectionView?

### ISSUE THREAD

**Issue by theofficejackpot** [cbpowell/MarqueeLabel#259]
iOS 14, iPhone, Swift.

I can get MarqueeLabel working on a normal UILabel from Storyboard within a UIView.

I cannot, however, get it working from within a TableView Cell -> UICollectionView (horizontal flow)

I tried from cellForRow and willDisplay in collection view delegate, but neither starts the scrolling.  I tried .restartLabel() and .labelize = false.

**Comment by cbpowell** [comment]
Hey! It would be awhile before I could get around to adding that to the demo (unless you happen to have a good "basic" collection view setup you could provide?).

Are you using a table view inside a collection view? So you have something like multiple independent table views, each inside a view of a collection view? Regardless, I don't think your use case would prevent MarqueeLabel from working - underneath the hood it's just some animations, and as far as I know should work fine anywhere.

The root of the problem as I think you already figured out is that the labels need to be manually started, which makes sense in situations where they are embedded in things like table views. Your issue might be finding the right place to start the onscreen labels (if I'm understanding your view hierarchy).

First, I'd recommend reading my response on issue #258 to try and debug:
1. Make sure things are actually hooked up like you expect - e.g. you aren't calling `restartLabel` on a nil instance, and/or that the labels are actually MarqueeLabels and not regular UILabels (although calling `restartLabel` on a UILabel object will definitely cause a crash anyway!)
2. Confirm that your calls to trigger scrolling are actually getting to MarqueeLabel by setting a few breakpoints in the MarqueeLabel code for `restartLabel` or `triggerScrollStart` ([here](https://github.com/cbpowell/MarqueeLabel/blob/221e384acb3e36149ce2dfb2ad2e51570a9b5095/Sources/MarqueeLabel.swift#L1236-L1255))
3. Check then make sure MarqueeLabel is actually getting told to start scrolling, but failing for some reason - set breakpoints on the `returns` in [this area](https://github.com/cbpowell/MarqueeLabel/blob/221e384acb3e36149ce2dfb2ad2e51570a9b5095/Sources/MarqueeLabel.swift#L851-L887) like suggested on the other issue

**Comment by theofficejackpot** [comment]
See screenshots.  The collection width is 1550.  Label is about 1350.  I can get the top text outside of the tableview to scroll just fine.  I'll try to set a breakpoint.  I just tried triggerScrollStart but it didn't do anything.

<img width="496" alt="Screen Shot 2020-12-22 at 12 56 10 PM" src="https://user-images.githubusercontent.com/45904198/102918643-45452380-4455-11eb-893d-4035a000ef7e.png">
<img width="430" alt="Screen Shot 2020-12-22 at 12 55 19 PM" src="https://user-images.githubusercontent.com/45904198/102918645-45ddba00-4455-11eb-818f-8db6297b32d2.png">

**Comment by cbpowell** [comment]
Ah I see, thanks for the screenshots. Let me know what you find with checking breakpoints.

But just to double check - is the text string length shorter than the width of your MarqueeLabel view frame width? If your actual text is "Walmart Inc.", which I'm assuming is shorter than 1350 pt, it won't ever scroll even if you attempt to manually trigger it. MarqueeLabel only scrolls if the text won't fit in the available frame width.

**Comment by theofficejackpot** [comment]
Man, kudos to that discovery.  Once I dropped the label less than the text, it started scrolling.  Ok, now the real question - I want Marquee label to scroll the company name as they are horizontally scrolling through the details.  Should I add 1350 - len(company name) spaces to it to get it to scroll or is there a more elegant way?

**Comment by cbpowell** [comment]
Yep a bunch of spaces might be the fastest way, although I know that's not elegant. But if you just want the one string instance to loop around with a big empty space between instances, that's probably the fastest/easiest way!
