### ISSUE TITLE
Fade to right or left side ONLY

### ISSUE THREAD

**Issue by omarojo** [cbpowell/MarqueeLabel#267]
Could you add the fade effect to be configurable to be applied only to one side of the label ?
Right or Left or both, currently is both. 

That would be great. :)

**Comment by cbpowell** [comment]
Hi @omarojo - well it's not currently supported as a default setting, but I think you might be able to achieve what you want by creating your own [`scrollSequence`](https://github.com/cbpowell/MarqueeLabel/blob/8349b2c103825e5b33ced9c331c5a68d10921944/Sources/MarqueeLabel.swift#L70-L92)!

That property lets you define your own sequence of how the scroll animation works, by configuring how you want the various states to look, which edges to fade (leading or trailing), and when you want them to be achieved. I never got around to fully documenting it, but you can probably work through the code that defines the [default `scrollSequence` settings](https://github.com/cbpowell/MarqueeLabel/blob/8349b2c103825e5b33ced9c331c5a68d10921944/Sources/MarqueeLabel.swift#L691-L716) for the built-in scroll animations.

So for an example using the `.leftRight` type, the default `scrollSequence` is:
```swift
sequence = scrollSequence ?? [
    ScrollStep(timeStep: 0.0, position: .home, edgeFades: .trailing),               // Starting point, at home, with trailing fade
    ScrollStep(timeStep: animationDelay, position: .home, edgeFades: .trailing),    // Delay at home, maintaining fade state
    FadeStep(timeStep: 0.2, edgeFades: [.leading, .trailing]),                      // 0.2 sec after delay ends, fade leading edge in as well
    FadeStep(timeStep: -0.2, edgeFades: [.leading, .trailing]),                     // Maintain fade state until 0.2 sec before reaching away position
    ScrollStep(timeStep: animationDuration, timingFunction: animationCurve,         // Away position, using animationCurve transition, with only leading edge faded in
        position: .away, edgeFades: .leading),
    ScrollStep(timeStep: animationDelay, position: .away, edgeFades: .leading),     // Delay at away, maintaining fade state (leading only)
    FadeStep(timeStep: 0.2, edgeFades: [.leading, .trailing]),                      // 0.2 sec after delay ends, fade trailing edge back in as well
    FadeStep(timeStep: -0.2, edgeFades: [.leading, .trailing]),                     // Maintain fade state until 0.2 sec before reaching home position
    ScrollStep(timeStep: animationDuration, timingFunction: animationCurve,         // Ending point, back at home, with only trailing fade
        position: .home, edgeFades: .trailing)
]
```
To change that to one that doesn't have any trailing fades at any point, you'd create your own array/sequence, and then set it to the `scrollSequence` property of your label:
```swift
sequence = [
    ScrollStep(timeStep: 0.0, position: .home, edgeFades: []),               // Starting point, at home, with trailing fade
    ScrollStep(timeStep: animationDelay, position: .home, edgeFades: []),    // Delay at home, maintaining fade state
    FadeStep(timeStep: 0.2, edgeFades: .leading),                      // 0.2 sec after delay ends, fade leading edge in as well
    FadeStep(timeStep: -0.2, edgeFades: .leading),                     // Maintain fade state until 0.2 sec before reaching away position
    ScrollStep(timeStep: animationDuration, timingFunction: animationCurve,         // Away position, using animationCurve transition, with only leading edge faded in
        position: .away, edgeFades: .leading),
    ScrollStep(timeStep: animationDelay, position: .away, edgeFades: .leading),     // Delay at away, maintaining fade state (leading only)
    FadeStep(timeStep: 0.2, edgeFades: .leading),                      // 0.2 sec after delay ends, fade trailing edge back in as well
    FadeStep(timeStep: -0.2, edgeFades: .leading),                     // Maintain fade state until 0.2 sec before reaching home position
    ScrollStep(timeStep: animationDuration, timingFunction: animationCurve,         // Ending point, back at home, with only trailing fade
        position: .home, edgeFades: [])
]
aLabel.scrollSequence = sequence
```
Note that I essentially just removed all instances of `.trailing` on the `edgeFades:` arguments, replacing the ones where it was only `.trailing` with an empty set (the `EdgeFade` custom type inherits from `OptionSet`).

The caveat is you'd need to grab the right values to use for `animationDelay`, `animationDuration`, and `animationCurve`, but those are all just properties you set to configure your label (or use default values). The `.continuous` type labels will be a little more complicated depending on how fancy you get, as MarqueeLabel [does some math](https://github.com/cbpowell/MarqueeLabel/blob/8349b2c103825e5b33ced9c331c5a68d10921944/Sources/MarqueeLabel.swift#L653) to determine the fade in point…but only to be fancy, you could empirically determine that value based on your specific fade length too.

The documentation on `ScrollStep`, `FadeStep`, and the various associated supporting code is [located here](https://github.com/cbpowell/MarqueeLabel/blob/8349b2c103825e5b33ced9c331c5a68d10921944/Sources/MarqueeLabel.swift#L1613).

I realize that's probably more complicated than you wanted, but hope you find it useful! In general this approach is more flexible but may not have been used much by others so it certainly has room for improvement.

**Comment by cbpowell** [comment]
Closing this for now, as it is supported with a custom scroll sequence at least - let me know if it didn’t end up working well for you!
