### ISSUE TITLE
Get percentage of animation executed

### ISSUE THREAD

**Issue by alexandre-odet** [cbpowell/MarqueeLabel#269]
### Usage Details
  - Language: Swift
  - Platform: iPhone/iPad
  

### Actual Behavior
When the label's frame is updated, the animation is played from the beginning again.
As I subclassed it and added an animation repeat, I would like to play my animation only 2 times, and I was thinking about using an animation percentage being executed to avoid an infinite loop of animations.

I have an infinite animation loop because when `labelReturnedToHome(_ finished: Bool)` is called, I use the finish flag to detect if yes or no animation was played.
But the label's frame was updated before animation ended properly, so I never counted it.

Ignoring the `finished` flag is not a good idea, because everytime `layoutSubviews()` is called `returnToHome()` is called either, and it would send the `labelReturnedToHome(_ finished: Bool)` with false, without having the animation started. 

In my mind, calculating an animation percentage is a good idea, because if animation has not started (percentage equal to 0) you can ignore this event and do not count it for nothing.

Have you an idea about writing it in an elegant way ?

**Comment by cbpowell** [comment]
Hmm interesting problem!

First of all, your issue made me realize that `labelReturnedToHome()` is in fact NOT being called when the internal/private `returnLabelToHome()` function is used. That function is utilized by `updateAndScroll()` - which is the main function used when a property changes that causes an animation recompute and (potential) restart. That's definitely not the intent, and I'm surprised it's taken this long to come up!

So in actuality you _should_ have been getting a `labelReturnedToHome()` call with `finished` set to false whenever the frame is changed, but weren't. When it's working correctly, would that help your issue?

If not - you can check if the label animation is in-flight via the `awayFromHome` boolean property. A true value for that is equivalent to a 0% animation progress state.

**Comment by cbpowell** [comment]
Sure thing! Also I didn't mean to imply I'm against a property like that, I was just looking to get you a rapid solution. I had started something similar for #249, which maybe I should revisit as well.

I've added an `animationPosition` property in the latest commits, along with the other correction I described above, if you want to try it out. Not exactly the same implementation as yours, but I suspect you can modify the results as you'd like?

And noted on the feature to allow the animation to complete - I haven't worked on it, but perhaps I'll try to take a look!

**Comment by cbpowell** [comment]
I added this feature in [release 4.3.0](https://github.com/cbpowell/MarqueeLabel/releases/tag/4.3.0), hopefully it helps your use case!
