### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by rastaman111** [cbpowell/MarqueeLabel#271]
The application gives an error to me.
My application has 2 screens, and when I go to 2 it gives an error

@IBOutlet weak var titleLabel: MarqueeLabel!
This used to work

I attach the screen
![image](https://user-images.githubusercontent.com/15727518/132857714-619c7460-0d22-4935-ab77-bc0acea2c658.png)

**Comment by cbpowell** [comment]
Make sure the custom class for that label instance in Interface Builder is also set to a MarqueeLabel class. Those types of errors pop up when you try to use a property of MarqueeLabel on a normal UILabel.

**Comment by rastaman111** [comment]
![image](https://user-images.githubusercontent.com/15727518/132879412-91b3fb37-b6cb-4ff2-8420-92f3e70cbb2d.png)
![image](https://user-images.githubusercontent.com/15727518/132879423-2c2ec634-5c47-43fd-9436-86149ba3a1a2.png)

This is how I have it configured.

**Comment by cbpowell** [comment]
How are you including MarqueeLabel in your project? Cocoapods/Carthage/SPM or direct import?

It might be the Module field, although offhand I don’t remember exactly what that needs to be. Maybe try setting/resetting the Module value?

**Comment by rastaman111** [comment]
I connect via SPM.

**Comment by cbpowell** [comment]
Appears to work fine for me - you may need to set the Module field to MarqueeLabel as well, as shown below in my test case below. I'd suggest trying a few combinations of that field along with the Inherit setting.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/593953/132957200-aa738e80-2e2d-413b-a5bd-bcb32cfcefaa.png">

**Comment by rastaman111** [comment]
> Appears to work fine for me - you may need to set the Module field to MarqueeLabel as well, as shown below in my test case below. I'd suggest trying a few combinations of that field along with the Inherit setting.
> 
> 
> 
> <img width="771" alt="image" src="https://user-images.githubusercontent.com/593953/132957200-aa738e80-2e2d-413b-a5bd-bcb32cfcefaa.png">
> 
> 

This solution helped to solve the problem
