### ISSUE TITLE
Fixed duration for variable length of string

### ISSUE THREAD

**Issue by iZeDeveloper** [cbpowell/MarqueeLabel#277]
is it possible to have a same scroll speed so that long and small text scroll's at constant speed, right now the speed varies for different lengths of strings. any help would be appreciated. thanks

**Comment by cbpowell** [comment]
Yep! You can [set a rate SpeedLimit](https://github.com/cbpowell/MarqueeLabel/blob/e916aa842beccf6fdbdecfed90819449a65e541c/Sources/MarqueeLabel.swift#L274) instead of a duration. You could set the same rate to both, although they won’t necessarily be exactly in sync.
