### ISSUE TITLE
Not an issue, just a question about changing text while scrolling

### ISSUE THREAD

**Issue by Spencer-Villarreal** [cbpowell/MarqueeLabel#280]
I am wondering if there is a way that I can update the text while it is scrolling instead of it restarting from the beginning.

I have the label set up as a scrolling stock market prices area. Every 15 seconds I pull the new price of the stock tickers and update the Marquee label. When I do this is when the label starts back at the beginning.

I was going to try to use animationDidStop to change the text before the next scroll but for some reason, it gets called 4-5 times when updating the text.

Also, I am using attributedText to change the color of the prices between green and red.

**Comment by cbpowell** [comment]
Hi! So unfortunately MarqueeLabel doesn't currently support that. Not to say it couldn't, and I might look into that when I have time. There are some things to work through to do that though, such as how the scroll animation needs to readjust if the length of the text changes.

I would recommend you look into doing your stock ticker with a UICollectionView (or similar) though. With a collection view you can inherently update any sub-view (e.g., each stock) easily and independently, vs. with MarqueeLabel you just have one big single text string. You can animate the collection view scroll as well, and do a variation on infinite scrolling to just keep looping through the tickers you want. Hope this helps!
