### ISSUE TITLE
Randomly i get a crash in updateAndScroll function 

### ISSUE THREAD

**Issue by ShehataG** [cbpowell/MarqueeLabel#283]
While running the application sometimes i get a crash on line function  **private func updateAndScroll(overrideHold: Bool) {**

            case .continuousReverse, .rightLeft:
                labelFrame = bounds.divided(atDistance: leadingBuffer, from: CGRectEdge.maxXEdge).remainder.integral // Here this line 
            default:
                labelFrame = CGRect(x: leadingBuffer, y: 0.0, width: bounds.size.width - leadingBuffer, height: bounds.size.height).integral
            }

The crash says 

        Thread 1: signal SIGABRT

**Comment by ShehataG** [comment]
Yes it's xcode 14 beta 1 that i'm currently running

**Comment by cbpowell** [comment]
Yeah then you’ll run into that issue - would recommend updating to beta 2 when you can in order to fix it!

**Comment by cbpowell** [comment]
Yes I think so, definitely follow up here if updating to beta 2 doesn’t resolve it!
