### ISSUE TITLE
Please bump iOS version in podspec to 14.0

### ISSUE THREAD

**Issue by george-hito-skydio** [cbpowell/MarqueeLabel#292]
After upgrading to latest command line tools I started seeing failures during pod linking related to libarclite missing: https://developer.apple.com/forums/thread/728021
https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3

Nothing I tried worked until I manually went into `/Users/ghito/.cocoapods/repos/trunk/Specs/d/f/c/MarqueeLabel/4.3.1/MarqueeLabel.podspec.json` and bumped the iOS version to be 14.0. Could you please make this the default in MarqueeLabel?

**Comment by cbpowell** [comment]
The minimum deployment version is now iOS 11.0 in v4.3.2 (see #293), which hopefully fixes your issue. Let me know if not!
