### ISSUE TITLE
Too low iOS deployment target for Xcode 14

### ISSUE THREAD

**Issue by ale-gen** [cbpowell/MarqueeLabel#293]
While running my iOS app with target 12.0 in Xcode 14 (my app uses MarqueeLabel integrated by Pods) I get warning `The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99.`. It is caused that Xcode 14 minimum version support is 11.0. Is it possible to raise the deployment target of MarqueeLabel to 11.0?

The same issue (I mean target 9.0 instead 11.0) causes unsuccessful build for only MarqueeLabel target, which fails with error described [here](https://developer.apple.com/forums/thread/728021).

**Comment by cbpowell** [comment]
I pushed the v4.3.2 release to incorporate this - thanks for making the changes!
