### ISSUE TITLE
Larger text sizes / maximumContentSizeCategory 

### ISSUE THREAD

**Issue by iDevelopper** [cbpowell/MarqueeLabel#295]
### Usage Details
  - Language: Swift and Objective-C
  - Platform: iPhone/iPad
  - iOS Version: iOS 15 +
  

### Expected Behavior
Should limit the text size when larger text sizes are used.

### Actual Behavior
maximumContentSizeCategory does not work with MarqueeLabel, works fine on UILabel

### Steps to Reproduce the Problem
```swift
    @IBOutlet weak var label: MarqueeLabel! {
        didSet {
            let font = UIFont.systemFont(ofSize: UIFont.systemFontSize, weight: .regular)
            label.font = UIFontMetrics(forTextStyle: .body).scaledFont(for: font)
            label.adjustsFontForContentSizeCategory = true
            label.maximumContentSizeCategory = .small
        }
    }
```
Same issue with code (no Storyboard).

**Comment by iDevelopper** [comment]
I found that MarqueeLabel should have a setter for adjustsFontForContentSizeCategory which is missing:

In MarqueeLabel.m
```objective-c
- (void)setAdjustsFontForContentSizeCategory:(BOOL)adjustsFontForContentSizeCategory {
    [super setAdjustsFontForContentSizeCategory:adjustsFontForContentSizeCategory];
    self.subLabel.adjustsFontForContentSizeCategory = adjustsFontForContentSizeCategory;
}
```
In MarqueeLabel.swift
```swift
    open override var adjustsFontForContentSizeCategory: Bool {
        didSet {
            sublabel.adjustsFontForContentSizeCategory = self.adjustsFontForContentSizeCategory
        }
    }
```

**Comment by LeoNatan** [comment]
It should also probably override [`traitCollectionDidChange(_:)`](https://developer.apple.com/documentation/uikit/uitraitenvironment/1623516-traitcollectiondidchange) and perform the appropriate layout in response to content size category changes.

**Comment by cbpowell** [comment]
Thanks for the heads up that these are missing! Will get them added.

**Comment by cbpowell** [comment]
Added these in v4.4.0, although not the `traitCollection` stuff - I _think_ that gets caught in `layoutSubviews` like you mentioned, and some of that is only available to view controllers anyway it seems.

**Comment by LeoNatan** [comment]
@cbpowell UIView should get all the callbacks too, as it too is a `UITraitEnvironment`. But yeah, probably `layoutSubviews()` is enough.

**Comment by mickyzinho** [comment]
Does this also work for you when using attributed Text? Using text seems to work fine for me, but setting `attributedText` makes the font grow larger than the specified maximum content category.

**Comment by cbpowell** [comment]
@mickyzinho it should, though I admit I haven't checked against all cases lately. Could you give an example that causes it?

**Comment by iDevelopper** [comment]
It works for me.
