### ISSUE TITLE
Privacy Manifests

### ISSUE THREAD

**Issue by wlxo0401** [cbpowell/MarqueeLabel#296]
I don't have a bug, but I have a question.

Is MarqueeLabel not related to privacy manifest?

Read [Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc), which say:

----
From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

**Comment by wlxo0401** [comment]
I checked the revised one late.


v4.4.0

**Comment by wlxo0401** [comment]
![스크린샷 2023-12-12 오후 3 49 08](https://github.com/cbpowell/MarqueeLabel/assets/57979066/57bf0119-be5b-4518-8eff-0e7354839dc5)
I checked that Manifest was included, but it seems that the results of the archive are not included in the Privacy Report.

<img width="984" alt="스크린샷 2023-12-12 오후 3 50 59" src="https://github.com/cbpowell/MarqueeLabel/assets/57979066/30d7379e-ee26-4a2d-8800-98b7ea3fc69e">
When I check the library file, Privacy Manifest exists in 'ZIPFoundation' and 'MarqueeLabel', but only 'ZIPFoundation' exists in Privacy Report.

**Comment by cbpowell** [comment]
Thanks for the heads up! I'm guessing it's not getting put into the framework/package correctly. I'll take a look into it!

**Comment by wlxo0401** [comment]
@cbpowell 

thank you for the reply.

I will test it when you update.

**Comment by cbpowell** [comment]
Just as an update, I'm waiting on some feedback from Apple on this one. I was able to replicate the ZIPFoundation report output while playing with the manifest contents, so it seems to be included correctly at least. But the question is what the correct manifest content is for a library like MarqueeLabel that collects zero data.

**Comment by wlxo0401** [comment]
> Just as an update, I'm waiting on some feedback from Apple on this one. I was able to replicate the ZIPFoundation report output while playing with the manifest contents, so it seems to be included correctly at least. But the question is what the correct manifest content is for a library like MarqueeLabel that collects zero data.

I tested other libraries and found a lot of the same results. 
Apple says it will be implemented in the spring, but it is too quiet..

**Comment by wlxo0401** [comment]
> Thanks for the heads up! I'm guessing it's not getting put into the framework/package correctly. I'll take a look into it!

I discovered a new fact while testing. Until now, most of the libraries that have added PrivacyInfo have not been marked in PrivacyReport. 

However, when an item is added to the 'Personal Information Nutrition Label Type', the library name is displayed in the personal information protection report. 

Many libraries have updated PrivacyInfo without adding anything from Privacy Nutrition Label Types.

Does anyone know about this? Is "Privacy Nutrition Label Types" a must-have item?

Please feel free to leave your opinion.

**Comment by cbpowell** [comment]
I heard back from Apple - the correct approach is to have the appropriate keys in the Privacy Manifest, but with empty arrays (which is what MarqueeLabel has now). Thanks for the patience on this one!
