### ISSUE TITLE
UIView Animations when Labels are paused

### ISSUE THREAD

**Issue by johnalanwoods** [cbpowell/MarqueeLabel#32]
Hi,

First I would just like to say, fab control - thanks alot.

I noticed a potential bug using MarqueeLabel in my app.

I'm using it to show FX prices tick by, and when I get new prices I like to fade the alpha value of the MarqueeLabel in and out using a UIVIew animation block. The animation is to signify the change in price.

This all works well unless the label is paused, if it is paused and I try to animate (say the alpha value) it stops responding. It won't reanimate if I try to unpause it etc.

Not sure if this is really a bug but just wanted to get your thoughts...

PS. my current workaround is to basically unpause and repause after the animation is complete, this works, but unfortunately the label drifts by for a moment while the animation is in progress, which kind of defeats the purpose of the original pause.

Thanks again,
Kind Regards,
John

**Comment by cbpowell** [comment]
With all the BTC madness of late, I remembered this wallet… @johnalanwoods I'll take some of those bitcoin now! 😉

**Comment by johnalanwoods** [comment]
OK I feel very bad! I never sent you any Bitcoin!

I've moved on to another Cryptocurrency called Monero (it's like BTC but private, and better).

You can get a wallet here: https://mymonero.com/#/

Open one and this time I will send you some Crypto!

Trust me, like it was then, this is worth your time.

**Comment by cbpowell** [comment]
No need to feel bad! I just thought it was funny looking back, and I really appreciate your support!

I'll give Monero a shot! My wallet address is:
47G131LRmsojiQS1k4ePeSfqiDvgrTh4fFroPeKSU9ZkChj7kAhBsqgSAv2tFZLaTibhKSsdCznCi8BZeHpNSyacNwUPdeA

**Comment by johnalanwoods** [comment]
Perfect! Good man! Will reply when I’ve sent it over. Christmas has me offline last few days :)

**Comment by johnalanwoods** [comment]
@cbpowell OK my friend! I sent enough for a pizza and a couple of beers.

Each coin trades at ~350usd currently.

Enjoy, I think Monero is a fantastic project, you can check out peoples sentiment online, it's gaining a lot of popularity.

Any questions just shout, let me know if you get it.

(one last thing, always use the 'low priority' fee when sending XMR, it's nearly always included in the next block and costs cents to send rather than dollars).

**Comment by cbpowell** [comment]
You rock man! Much appreciated! And I do plan on looking into Monero some more, thanks for the information.

**Comment by johnalanwoods** [comment]
No probs my man!
