### ISSUE TITLE
marqueeLable Not working in CustomUitableview Cell

### ISSUE THREAD

**Issue by milindphirake** [cbpowell/MarqueeLabel#33]
Hi 

This is really nice Class.

I used it two places.
1) on viewcontroller header label to set header of scree.

It is working fine for me.

Issue=> 
1. But This lable is not working in my custom table cell

I am having three subview in custom cell and i want to pul this lable in each subview and scroll it.

**Comment by Insider77** [comment]
try 
`myLabel.setNeedsLayout()`

in your 

`func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {`

this helped me
