### ISSUE TITLE
Can't set marqueelabel in block

### ISSUE THREAD

**Issue by jacks8x** [cbpowell/MarqueeLabel#62]
Hi, I have set marqueelabel, it works great everywhere except in block. I have a method which request data from server, after got data it call back in block, and then I set the text for MarqueeLabel, but it can't scroll

**Comment by cbpowell** [comment]
Going to close this for now, since I'm guessing you've solved your issue or moved on to another implementation. Feel free to comment/reopen if you think there's still an issue with MarqueeLabel!
