### ISSUE TITLE
Scrolling stops

### ISSUE THREAD

**Issue by kikivg** [cbpowell/MarqueeLabel#66]
I have a view which is a subview of my base VC's view and in this view I have MarqueeLabel. When I click on this view modal view controller is presented. So, when I close modal view controller, animation stops. I tried to use `restart label` or `[MarqueeLabel controllerViewAppearing:self];` in VC but animation won't scroll again. When I reconfigure my label on return from modal view, animation scrolls, but if I then again present modal view and go back from it, animation stops.

**Comment by anismansuri** [comment]
If you are using TableviewCell or CollectionViewCell, use this method
override func prepareForReuse() {
        super.prepareForReuse()
        yourObject.restartLabel()
    }
