### ISSUE TITLE
Wanting to start scroll automatically once, then wait for taps after that. 

### ISSUE THREAD

**Issue by pip8786** [cbpowell/MarqueeLabel#85]
As the title said, I want to have the label scroll through one time on appear and then wait for taps after that to repeat the scrolling. 
My first solution was to set `tapToScroll = YES` and then in my `viewdidappear` call:
```
    self.titleLabel.holdScrolling = YES;
    self.titleLabel.holdScrolling = NO;
```
The other way that worked for me was:
```
    [self.titleLabel performSelector:NSSelectorFromString(@"beginScroll") withObject:nil afterDelay:0];
```
which seemed only a little bit cleaner. 

Do you have any recommendation for this scenario?

**Comment by cbpowell** [comment]
Added this in [release v2.2.0](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.2.0) - thanks!
