### ISSUE TITLE
Frame not updated using autolayout inside navigationbar

### ISSUE THREAD

**Issue by AvdLee** [cbpowell/MarqueeLabel#87]
I'm having issues with the frame which wont update using MarqueeLabel. Everything works fine using UILabel instead.

This is my code:

        self.titleLabel = MarqueeLabel()
        self.titleLabel.style = .NavigationBarTitle
        self.titleLabel.rate = 16.0;
        self.titleLabel.fadeLength = 0.0;
        self.titleLabel.marqueeType = .MLContinuous;
        self.titleLabel.trailingBuffer = 10.0;
        self.titleLabel.animationDelay = 1.0;
        self.titleLabel.text = "TEST"
        self.addSubview(self.titleLabel)
        
        self.titleLabelLeftConstraint = self.titleLabel.autoPinEdge(ALEdge.Left, toEdge: ALEdge.Left, ofView: self, withOffset: 12)
        self.titleLabel.autoPinEdge(ALEdge.Right, toEdge: ALEdge.Right, ofView: self, withOffset: -12)
        self.titleLabel.autoAlignAxis(ALAxis.Horizontal, toSameAxisOfView: self, withOffset: 2)

It's inside a custom UINavigationbar, added as a subview. 
Note here is that I'm using TEST to fix this problem, but without TEST and setting the label in the viewwillappear of the first viewcontroller I'm showing keeps the label at a height of zero.

Any fixes without TEST would be appreciated, as some viewcontroller without a title will show up with TEST as a title, which is not what we want :)

**Comment by cbpowell** [comment]
Another thought - in my experience with messing with custom UINavigationBars, it really tries hard to location and size all its subviews the way it wants (especially during `layoutSubviews`).

Have you looked at what MarqueeLabel's [`sizeThatFits:`](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L453) and [`intrinsicContentSize`](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L1142) methods are returning, relative to the size you *want/expect*? I would have though the AL constraints would override that, but maybe not?

**Comment by cbpowell** [comment]
Going to go ahead and close this one due to inactivity - please follow up (and I'll reopen) if you're still having an issue caused by MarqueeLabel!
