### ISSUE TITLE
SIGABRT at runtime at property setter

### ISSUE THREAD

**Issue by SilverEnderman** [cbpowell/MarqueeLabel#89]
Using the code below, I am thrown a `Thread 1: signal SIGABRT` at runtime on the lines where I set marqueeType, trailingBuffer, rate, and fadeLength properties. I am only thrown the error on the first such call, but that may simply be the nature of the error.

    // collectionView:cellForItemAtIndexPath
    
    UICollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"Cell" forIndexPath:indexPath];
    
    MarqueeLabel *showLabel = (MarqueeLabel *)[cell viewWithTag:200];
    showLabel.marqueeType = MLContinuous;
    showLabel.trailingBuffer = 24.0;
    showLabel.rate = 27.0;
    showLabel.fadeLength = 12.0;

Here, the label is contained within the content view of a`UICollectionViewCell`, and "Cell" is the `reuseIdentifier`. The label's `tag` property is set to 200 in Interface Builder.

I am unsure what may be causing the issue, whether it is my own code, implementation, or something else. I have tried using the setter methods for each property, but the same result is returned.

Some assistance would be helpful, as I have very little experience with tracking down SIGABRT and other errors. Thank you.

**Comment by cbpowell** [comment]
(On mobile so I can give a totally complete answer) I suspect the call to viewWithTag maybe isn't actually returning an instance of MarqueeLabel? Then when you attempt to set the properties, you get a SIGABRT because the object returned doesn't respond to those methods.

I suggest setting a breakpoint right after using viewWithTag so you can inspect the object returned and can confirm it is actually a MarqueeLabel. Might just be you've got the tag number wrong!

**Comment by SilverEnderman** [comment]
After placing a breakpoint after `viewWithTag`, I find that it returns an instance of `UILabel`, and not `MarqueeLabel` as expected. Upon further inspection of the console (I really should have done this earlier) an `Unknown class MarqueeLabel in Interface Builder file` message is displayed. I removed MarqueeLabel from the Custom Class inspector on the label in question, then found it in the drop-down menu, with the same result. Adding `MarqueeLabel.h` to the precompiled header didn't help either.

I tried uninstalling the Pod from the CocoaPods setup, and now it works perfectly. Not sure what the issue was there, but at least it works now! Thanks for the help. :)

**Comment by cbpowell** [comment]
Awesome! Figured that was probably the case.

**Comment by akashgupta88** [comment]
@cbpowell I recently got ownership of a codebase which uses MarqueeLabel just as @SparrowBlaze  has described above... By manual inclusion of the class files. We tried moving the dependency to CocoaPods and faced the issue `Unknown class MarqueeLabel in Interface Builder file`.

**Comment by cbpowell** [comment]
@akashgupta88 were you able to resolve your issue? There shouldn't be any problems with using MarqueeLabel as a Cococapods dependency - assuming it's set up correctly the MarqueeLabel classes should be available just like a "regular" included file.
