### ISSUE TITLE
Label doesn't scroll if it doesn't exist within a view controller

### ISSUE THREAD

**Issue by codyd51** [cbpowell/MarqueeLabel#90]
For a jailbroken application I'm working on, I need a scrolling label added to a view within SpringBoard. However, there isn't a view controller in the label's hierarchy, and as a result the MarqueeLabel is not scrolling.

As I understand it, the label will not scroll if a view controller is not detected. Is there any way around this behavior? Will there be any negative repercussions from commenting out this check for my use case?

Cheers,

-Phillip Tennen

**Comment by cbpowell** [comment]
I think you can probably comment out the check for a view controller, or really any of the checks in [`labelShouldScroll`](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L471) as long as they don't have any negative effects for your particular use case. They exist mostly to prevent some weirdness that was happening with animations firing before everything is "ready".

**Comment by codyd51** [comment]
Great, thanks!
