### ISSUE TITLE
When labelize is set to YES, there should be an option to set the numberOfLines to 0 to allow multiline text for labels

### ISSUE THREAD

**Issue by shankqr** [cbpowell/MarqueeLabel#91]
suggestion:

- (void)setLabelize:(BOOL)labelize {
    if (_labelize == labelize) {
        return;
    }
    
    _labelize = labelize;
    
    if (labelize)
    {
        self.subLabel.numberOfLines = 0;
    }
    else
    {
        self.subLabel.numberOfLines = 1;
    }
    
    [self updateSublabelAndLocationsAndBeginScroll:YES];
}

**Comment by cbpowell** [comment]
Thanks for the suggestion! However I'd like to keep MarqueeLabel focused on the original intent, which is to emulate the style Apple uses in their own apps (particularly the Podcast app). I haven't tried the above code, but if it works you can of course branch off with those modifications for your use case.
