### ISSUE TITLE
Option to allow text to move like a Marque even if the text width is shorter than the label width

### ISSUE THREAD

**Issue by shankqr** [cbpowell/MarqueeLabel#92]
Sometimes a short text should be a Marquee because it is cool! Agree?

**Comment by cbpowell** [comment]
Thanks again - I'll have to lean on my response in issue #91 as well though, in that I'd like to keep MarqueeLabel close to Apple's implementation. I think there might be one or two other libraries out there that do this kind of always-scrolling marquee (more like a news ticker)?
