### ISSUE TITLE
There are still have problem in iOS8.0

### ISSUE THREAD

**Issue by matthewyan** [cbpowell/MarqueeLabel#93]
I've found that some system version string is:"8.0" not "8.0.0"

So, I change the version function:
<code>
- (BOOL)isIOS80xVersion
{
    NSString *ver = [[UIDevice currentDevice] systemVersion];
    if ([ver hasPrefix:@"8.0"]) {
        return YES;
    }
    return NO;
}
</code>

and this will work fine on all iOS8.0.x system

**Comment by cbpowell** [comment]
Thanks for letting me know! I admittedly grabbed the code for the iOS version check from a StackOverflow answer after looking through a few options. I'll fix this shortly in release v2.2.1.

**Comment by cbpowell** [comment]
Fixed this in [release v2.2.1](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.2.1), thanks!
