### ISSUE TITLE
Marquee Label not scrolling

### ISSUE THREAD

**Issue by sreelash** [cbpowell/MarqueeLabel#94]
I am using autoayout in iOS 8.0. I integrated the library as mentioned in the github. But the control is not scrolling. I have used the following code:

self.footerLabel.marqueeType = MLContinuous;
    self.footerLabel.scrollDuration = 15.0;
    self.footerLabel.animationCurve = UIViewAnimationOptionCurveEaseInOut;
    self.footerLabel.fadeLength = 10.0f;
    self.footerLabel.leadingBuffer = 30.0f;
    self.footerLabel.trailingBuffer = 20.0f;
    self.footerLabel.tag = 101;
    self.footerLabel.text = @"This is a test of MarqueeLabel - the text is long enough that it needs to scroll to see the whole thing.";

Since this was not working, I tried adding the line [self.footerLabel restartLabel];. Eventhough it did not work. Then I tried the adding the following line of code 

[MarqueeLabel controllerViewWillAppear:self]; 

in viewWillAppear, viewDidAppear and viewDidLayoutSubviews. Nothing worked for me.

I am getting the following meesage on console "MarqueeLabel: Failed to find t for Y input!".  Can you help me to resolve this issue.

Thanks and regards,
Sree

**Comment by cbpowell** [comment]
This might be related to issue #93, if you are indeed using iOS 8.0.x and not iOS 8.1+. @matthewyan pointed out that the version check wasn't catching anything other than iOS 8.0.0, and not 8.0.1/8.0.2. Try updating to [release v2.2.1](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.2.1) and see if things are fixed.

**Comment by cbpowell** [comment]
I'm going to assume that release 2.2.1 fixed your issue, so I'll go ahead and close this issue.
