### ISSUE TITLE
Marquee Label Does't Accept More than 250 KB

### ISSUE THREAD

**Issue by pothirajp** [cbpowell/MarqueeLabel#95]
i m using Marquee label in my project. if i assign value (less than 240KB) its woking fine. if i give more than 250 KB or Moe data its not working. Can u give me the solution

**Comment by cbpowell** [comment]
I expect 250 kB is more text than UILabel can handle (MarqueeLabel uses UILabel internally). You probably need to investigate alternatives to MarqueeLabel/UILabel for that much text.
