### ISSUE TITLE
holdScrolling not working correctly

### ISSUE THREAD

**Issue by kmckinley** [cbpowell/MarqueeLabel#97]
Scrolling will occur when I set holdScrolling to YES.  The issue stems from restartLabel and triggerScrollStart.  Seems these both should also check the holdScrolling property.

```
 - (void)restartLabel {
-    if (self.labelShouldScroll && !self.tapToScroll) {
+    if (self.labelShouldScroll && !self.tapToScroll && !self.holdScrolling) {
         [self beginScroll];
     }
 }

 - (void)triggerScrollStart {
-    if (self.labelShouldScroll && !self.awayFromHome) {
+    if (self.labelShouldScroll && !self.awayFromHome && !self.holdScrolling) {
         [self beginScroll];
     }
 }
```

**Comment by cbpowell** [comment]
Good catch - the `restartLabel` method definitely should hold scrolling if `holdScrolling == YES`. However, the `triggerScrollStart` is actually functioning as intended, as it by definition "overrides any non-size" reason (i.e. it won't force a too-short label to scroll) that the label isn't automatically scrolling.

**Comment by kmckinley** [comment]
Ah That makes sense.  I can change update my pull request to revert the triggerScrollStart back.
