### ISSUE TITLE
AttributedText color gets overridden when text is long enough to scroll

### ISSUE THREAD

**Issue by kmckinley** [cbpowell/MarqueeLabel#98]
When applying AttributedText NSForegroundColorAttributeName the colors being set will be overridden when the text is long enough to require scrolling.  The issue seems to stem from refreshSubLabels:.  Removing "sl.textColor = self.textColor;" seems to fix the issue.

```
- (void)refreshSubLabels:(NSArray *)subLabels {
    for (UILabel *sl in subLabels) {
        sl.attributedText = self.attributedText;
        sl.backgroundColor = self.backgroundColor;
//        sl.textColor = self.textColor;
        sl.shadowColor = self.shadowColor;
        sl.shadowOffset = self.shadowOffset;
        sl.textAlignment = NSTextAlignmentLeft;
    }
}
```

**Comment by cbpowell** [comment]
Could you give a little more detail about how you're running into this? Not that I don't believe you're getting it - but I've had some trouble with maintaining compatibility for both attributed and non-attributed strings in the past (see #64). I also set up an additional demo continuous label with a text color via NSForegroundColorAttributeName, but currently I'm not getting it to replicate.

**Comment by kmckinley** [comment]
Not a problem at all.  I've subclassed MarqueeLabel to have a common init with the below setup:
```
- (void)commonInit {
    [self setFadeLength:15.0];
    [self setRate:30.0];
    [self setTrailingBuffer:self.frame.size.width];
    [self setLeadingBuffer:0.0];
    [self setAnimationDelay:2.0];
    [self setMarqueeType:MLContinuous];
}
```

Here is test code to demonstrate the attributedString issue:

```
NSRange greyRange = NSMakeRange(0, 5);
    NSRange redRange = NSMakeRange(greyRange.length, testString.length - greyRange.length);
    
    NSMutableAttributedString *text =[[NSMutableAttributedString alloc] initWithString:testString];
    [text addAttribute:NSForegroundColorAttributeName
                 value:[UIColor grayColor]
                 range:greyRange];
    [text addAttribute:NSForegroundColorAttributeName
                 value:[UIColor redColor]
                 range:redRange];
    [_someLabel setAttributedText:text];
```

Here is a screenshot with the textColor removed:
![Image of removed](https://s3.amazonaws.com/uploads.hipchat.com/61380/615578/zHNdIkGnAGGuAHl/Screen%20Shot%202015-04-17%20at%209.05.13%20AM.png)

Here is with textColor not removed:
![Image of not removed](https://s3.amazonaws.com/uploads.hipchat.com/61380/615578/6ICDxuLEDVQR5b7/Screen%20Shot%202015-04-17%20at%209.04.38%20AM.png)

**Comment by cbpowell** [comment]
Ah I should have thought of that, I was just setting up my test with a single text color throughout.

I'm thinking I might add a flag to keep track of if the label is being used with attributed text or not (i.e. `self.isAttributedLabel`), and utilize it in the `refreshSublabels` method to decide how to forward the label properties.

But before I do that, could you try just rearranging the order in which the properties are set? Try this out:
```objective-c
- (void)refreshSubLabels:(NSArray *)subLabels {
    for (UILabel *sl in subLabels) {
        sl.backgroundColor = self.backgroundColor;
        sl.textColor = self.textColor;
        sl.shadowColor = self.shadowColor;
        sl.shadowOffset = self.shadowOffset;
        sl.textAlignment = NSTextAlignmentLeft;
        // Move attributed label call to end
        sl.attributedText = self.attributedText;
    }
}
```

**Comment by kmckinley** [comment]
Yeah not a problem.  Just ran the code with the rearrangement, and it didn't fix the issue.

**Comment by kmckinley** [comment]
Something else I noticed when stepping through refreshSubLabels is that that attributedText isn't what I would have expected.
```
Petrichor-Music - Message to Bears - Daylight Goodbye{
    NSColor = "UIDeviceWhiteColorSpace 0.5 1";
}
```

It should be:
```
Petrichor-Music - {
    NSColor = "UIDeviceWhiteColorSpace 0.5 1";
}Message to Bears - Daylight Goodbye{
    NSColor = "UIDeviceWhiteColorSpace 0.333333 1";
}
```

**Comment by cbpowell** [comment]
If you're interested in trying a little more debugging, you could try adding this if statement:
```objective-c
- (void)refreshSubLabels:(NSArray *)subLabels {
    for (UILabel *sl in subLabels) {
        if (sl.tag == 700) {
            // Do not overwrite base subLabel properties
            continue;
        }
        sl.backgroundColor = self.backgroundColor;
        sl.textColor = self.textColor;
        sl.shadowColor = self.shadowColor;
        sl.shadowOffset = self.shadowOffset;
        sl.textAlignment = NSTextAlignmentLeft;
        // Move attributed label call to end
        sl.attributedText = self.attributedText;
    }
}
```
I think by setting the individual style properties like `textColor`, the attributed string is getting overwritten. All the `self` properties actually just pull from `self.subLabel`, so as this loops through and hits the "primary" subLabel, it basically blanks it's own `attributedText`.

**Comment by kmckinley** [comment]
Ah that makes a lot of sense.  I just tested the above code and it works perfectly.  Do you think there would be any side effects else where?

**Comment by cbpowell** [comment]
Don't think it should cause any side effects, that `refreshSublabels` method is only used in one place currently. Merged in the fix, with a few additions - thanks!
